// @generated drizzle-zero signature:sha256:9866996f76fdbfc2229827619ad97324d9177134f24a51d6a02be62513e53469
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { ReadonlyJSONValue, Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { CustomType } from "drizzle-zero";
import type * as drizzleSchema from "../../db/src/schema/index";

const accountTable = {
  name: "account",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    accountId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "account_id",
    },
    providerId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    accessToken: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "access_token",
    },
    refreshToken: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "refresh_token",
    },
    idToken: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "id_token",
    },
    accessTokenExpiresAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "access_token_expires_at",
    },
    refreshTokenExpiresAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "refresh_token_expires_at",
    },
    scope: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    password: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const advancePaymentTable = {
  name: "advancePayment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    city: {
      type: "string",
      optional: true,
      customType: null as unknown as "bangalore" | "mumbai",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as "pending" | "approved" | "rejected",
    },
    rejectionReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "rejection_reason",
    },
    bankAccountName: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_account_name",
    },
    bankAccountNumber: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_account_number",
    },
    bankAccountIfscCode: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_account_ifsc_code",
    },
    approvalScreenshotKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "approval_screenshot_key",
    },
    reviewedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "reviewed_by",
    },
    reviewedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "reviewed_at",
    },
    submittedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "submitted_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "advance_payment",
} as const;
const advancePaymentAttachmentTable = {
  name: "advancePaymentAttachment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    advancePaymentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "advance_payment_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as "file" | "url",
    },
    filename: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    objectKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "object_key",
    },
    url: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    mimeType: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "mime_type",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "advance_payment_attachment",
} as const;
const advancePaymentHistoryTable = {
  name: "advancePaymentHistory",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    advancePaymentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "advance_payment_id",
    },
    actorId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "actor_id",
    },
    action: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "approved"
        | "rejected"
        | "created"
        | "updated"
        | "submitted"
        | "invoice_submitted"
        | "invoice_updated"
        | "invoice_approved"
        | "invoice_rejected",
    },
    note: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    metadata: {
      type: "json",
      optional: true,
      customType: null as unknown as ReadonlyJSONValue,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "advance_payment_history",
} as const;
const advancePaymentLineItemTable = {
  name: "advancePaymentLineItem",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    advancePaymentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "advance_payment_id",
    },
    categoryId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "category_id",
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    sortOrder: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sort_order",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "advance_payment_line_item",
} as const;
const appConfigTable = {
  name: "appConfig",
  columns: {
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    value: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["key"],
  serverName: "app_config",
} as const;
const bankAccountTable = {
  name: "bankAccount",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    accountName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "account_name",
    },
    accountNumber: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "account_number",
    },
    ifscCode: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "ifsc_code",
    },
    isDefault: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_default",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "bank_account",
} as const;
const eventFeedbackTable = {
  name: "eventFeedback",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    eventId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "event_id",
    },
    content: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "event_feedback",
} as const;
const eventFeedbackSubmissionTable = {
  name: "eventFeedbackSubmission",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    eventId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "event_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    feedbackId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "feedback_id",
    },
    submittedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "submitted_at",
    },
  },
  primaryKey: ["id"],
  serverName: "event_feedback_submission",
} as const;
const eventImmichAlbumTable = {
  name: "eventImmichAlbum",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    eventId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "event_id",
    },
    immichAlbumId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "immich_album_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "event_immich_album",
} as const;
const eventInterestTable = {
  name: "eventInterest",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    eventId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "event_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as "pending" | "approved" | "rejected",
    },
    message: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    reviewedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "reviewed_by",
    },
    reviewedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "reviewed_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "event_interest",
} as const;
const eventPhotoTable = {
  name: "eventPhoto",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    eventId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "event_id",
    },
    r2Key: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "r2_key",
    },
    immichAssetId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "immich_asset_id",
    },
    mimeType: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "mime_type",
    },
    caption: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as "pending" | "approved" | "rejected",
    },
    uploadedBy: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "uploaded_by",
    },
    reviewedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "reviewed_by",
    },
    reviewedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "reviewed_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "event_photo",
} as const;
const eventReminderSentTable = {
  name: "eventReminderSent",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    eventId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "event_id",
    },
    instanceDate: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "instance_date",
    },
    intervalMinutes: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "interval_minutes",
    },
    sentAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sent_at",
    },
  },
  primaryKey: ["id"],
  serverName: "event_reminder_sent",
} as const;
const eventRsvpPollTable = {
  name: "eventRsvpPoll",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    eventId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "event_id",
    },
    targetChatJid: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "target_chat_jid",
    },
    targetChatSource: {
      type: "string",
      optional: false,
      customType: null as unknown as "event_group" | "team_group",
      serverName: "target_chat_source",
    },
    messageId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "message_id",
    },
    question: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    yesOptionHash: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "yes_option_hash",
    },
    noOptionHash: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "no_option_hash",
    },
    sentAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sent_at",
    },
    closedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "closed_at",
    },
  },
  primaryKey: ["id"],
  serverName: "event_rsvp_poll",
} as const;
const eventRsvpVoteTable = {
  name: "eventRsvpVote",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    pollId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "poll_id",
    },
    userId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    phone: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    voteMessageId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "vote_message_id",
    },
    selectedOptionHashes: {
      type: "json",
      optional: false,
      customType: null as unknown as string[],
      serverName: "selected_option_hashes",
    },
    selectedOption: {
      type: "string",
      optional: false,
      customType: null as unknown as "yes" | "no" | "unknown",
      serverName: "selected_option",
    },
    votedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "voted_at",
    },
  },
  primaryKey: ["id"],
  serverName: "event_rsvp_vote",
} as const;
const eventUpdateTable = {
  name: "eventUpdate",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    eventId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "event_id",
    },
    content: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as "pending" | "approved" | "rejected",
    },
    createdBy: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "created_by",
    },
    reviewedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "reviewed_by",
    },
    reviewedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "reviewed_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "event_update",
} as const;
const expenseCategoryTable = {
  name: "expenseCategory",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "expense_category",
} as const;
const notificationTopicPreferenceTable = {
  name: "notificationTopicPreference",
  columns: {
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    topicId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "topic_id",
    },
    emailEnabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "email_enabled",
    },
    whatsappEnabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "whatsapp_enabled",
    },
  },
  primaryKey: ["userId", "topicId"],
  serverName: "notification_topic_preference",
} as const;
const permissionTable = {
  name: "permission",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    category: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const reimbursementTable = {
  name: "reimbursement",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    city: {
      type: "string",
      optional: true,
      customType: null as unknown as "bangalore" | "mumbai",
    },
    expenseDate: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expense_date",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as "pending" | "approved" | "rejected",
    },
    rejectionReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "rejection_reason",
    },
    bankAccountName: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_account_name",
    },
    bankAccountNumber: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_account_number",
    },
    bankAccountIfscCode: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_account_ifsc_code",
    },
    approvalScreenshotKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "approval_screenshot_key",
    },
    reviewedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "reviewed_by",
    },
    reviewedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "reviewed_at",
    },
    eventId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "event_id",
    },
    submittedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "submitted_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const reimbursementAttachmentTable = {
  name: "reimbursementAttachment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    reimbursementId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "reimbursement_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as "file" | "url",
    },
    filename: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    objectKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "object_key",
    },
    url: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    mimeType: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "mime_type",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "reimbursement_attachment",
} as const;
const reimbursementHistoryTable = {
  name: "reimbursementHistory",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    reimbursementId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "reimbursement_id",
    },
    actorId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "actor_id",
    },
    action: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "approved"
        | "rejected"
        | "created"
        | "updated"
        | "submitted"
        | "invoice_submitted"
        | "invoice_updated"
        | "invoice_approved"
        | "invoice_rejected",
    },
    note: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    metadata: {
      type: "json",
      optional: true,
      customType: null as unknown as ReadonlyJSONValue,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "reimbursement_history",
} as const;
const reimbursementLineItemTable = {
  name: "reimbursementLineItem",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    reimbursementId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "reimbursement_id",
    },
    categoryId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "category_id",
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    sortOrder: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sort_order",
    },
    generateVoucher: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "generate_voucher",
    },
    voucherAttachmentId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "voucher_attachment_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "reimbursement_line_item",
} as const;
const roleTable = {
  name: "role",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    isSystem: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_system",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const rolePermissionTable = {
  name: "rolePermission",
  columns: {
    roleId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "role_id",
    },
    permissionId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "permission_id",
    },
  },
  primaryKey: ["roleId", "permissionId"],
  serverName: "role_permission",
} as const;
const scheduledMessageTable = {
  name: "scheduledMessage",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    message: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    scheduledAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "scheduled_at",
    },
    attachments: {
      type: "json",
      optional: true,
      customType: null as unknown as CustomType<
        typeof drizzleSchema,
        "scheduledMessage",
        "attachments"
      >,
    },
    createdBy: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "created_by",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "scheduled_message",
} as const;
const scheduledMessageRecipientTable = {
  name: "scheduledMessageRecipient",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    scheduledMessageId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "scheduled_message_id",
    },
    recipientId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "recipient_id",
    },
    label: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as "user" | "group",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "pending"
        | "sent"
        | "failed"
        | "cancelled",
    },
    error: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    sentAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "sent_at",
    },
    retryCount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "retry_count",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "scheduled_message_recipient",
} as const;
const sessionTable = {
  name: "session",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    token: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    ipAddress: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "ip_address",
    },
    userAgent: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "user_agent",
    },
    impersonatedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "impersonated_by",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
  },
  primaryKey: ["id"],
} as const;
const teamTable = {
  name: "team",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    whatsappGroupId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "whatsapp_group_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const teamEventTable = {
  name: "teamEvent",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    teamId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "team_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    location: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    city: {
      type: "string",
      optional: true,
      customType: null as unknown as "bangalore" | "mumbai",
    },
    startTime: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "start_time",
    },
    endTime: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "end_time",
    },
    isPublic: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_public",
    },
    whatsappGroupId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "whatsapp_group_id",
    },
    recurrenceRule: {
      type: "json",
      optional: true,
      customType: null as unknown as {
        rrule: string;
        exdates?: string[];
        excludeRules?: string[];
      },
      serverName: "recurrence_rule",
    },
    seriesId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "series_id",
    },
    originalDate: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "original_date",
    },
    cancelledAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "cancelled_at",
    },
    feedbackEnabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "feedback_enabled",
    },
    feedbackDeadline: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "feedback_deadline",
    },
    postRsvpPoll: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "post_rsvp_poll",
    },
    rsvpPollLeadMinutes: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "rsvp_poll_lead_minutes",
    },
    reminderIntervals: {
      type: "json",
      optional: true,
      customType: null as unknown as number[],
      serverName: "reminder_intervals",
    },
    reminderTarget: {
      type: "string",
      optional: true,
      customType: null as unknown as "participants" | "group" | "both",
      serverName: "reminder_target",
    },
    postEventNudgesEnabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "post_event_nudges_enabled",
    },
    createdBy: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "created_by",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "team_event",
} as const;
const teamEventMemberTable = {
  name: "teamEventMember",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    eventId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "event_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    addedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "added_at",
    },
    attendance: {
      type: "string",
      optional: true,
      customType: null as unknown as "present" | "absent",
    },
    attendanceMarkedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "attendance_marked_at",
    },
    attendanceMarkedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "attendance_marked_by",
    },
  },
  primaryKey: ["id"],
  serverName: "team_event_member",
} as const;
const teamMemberTable = {
  name: "teamMember",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    teamId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "team_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as "member" | "lead",
    },
    joinedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "joined_at",
    },
  },
  primaryKey: ["id"],
  serverName: "team_member",
} as const;
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    emailVerified: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "email_verified",
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    gender: {
      type: "string",
      optional: true,
      customType: null as unknown as "male" | "female",
    },
    dob: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    phone: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    isOnWhatsapp: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_on_whatsapp",
    },
    isActive: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_active",
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    banned: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    banReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "ban_reason",
    },
    banExpires: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "ban_expires",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const vendorTable = {
  name: "vendor",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    contactEmail: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "contact_email",
    },
    contactPhone: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "contact_phone",
    },
    bankAccountName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "bank_account_name",
    },
    bankAccountNumber: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "bank_account_number",
    },
    bankAccountIfscCode: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "bank_account_ifsc_code",
    },
    address: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    gstNumber: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "gst_number",
    },
    panNumber: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "pan_number",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as "pending" | "approved",
    },
    createdBy: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "created_by",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const vendorPaymentTable = {
  name: "vendorPayment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    vendorId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "vendor_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    invoiceNumber: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "invoice_number",
    },
    invoiceDate: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "invoice_date",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "pending"
        | "approved"
        | "rejected"
        | "partially_paid"
        | "paid"
        | "invoice_pending"
        | "completed",
    },
    rejectionReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "rejection_reason",
    },
    approvalScreenshotKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "approval_screenshot_key",
    },
    reviewedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "reviewed_by",
    },
    reviewedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "reviewed_at",
    },
    invoiceReviewedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "invoice_reviewed_by",
    },
    invoiceReviewedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "invoice_reviewed_at",
    },
    invoiceRejectionReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "invoice_rejection_reason",
    },
    city: {
      type: "string",
      optional: true,
      customType: null as unknown as "bangalore" | "mumbai",
    },
    eventId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "event_id",
    },
    submittedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "submitted_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "vendor_payment",
} as const;
const vendorPaymentAttachmentTable = {
  name: "vendorPaymentAttachment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    vendorPaymentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "vendor_payment_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as "file" | "url",
    },
    purpose: {
      type: "string",
      optional: true,
      customType: null as unknown as "quotation" | "invoice",
    },
    filename: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    objectKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "object_key",
    },
    url: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    mimeType: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "mime_type",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "vendor_payment_attachment",
} as const;
const vendorPaymentHistoryTable = {
  name: "vendorPaymentHistory",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    vendorPaymentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "vendor_payment_id",
    },
    actorId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "actor_id",
    },
    action: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "approved"
        | "rejected"
        | "created"
        | "updated"
        | "submitted"
        | "invoice_submitted"
        | "invoice_updated"
        | "invoice_approved"
        | "invoice_rejected",
    },
    note: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    metadata: {
      type: "json",
      optional: true,
      customType: null as unknown as ReadonlyJSONValue,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "vendor_payment_history",
} as const;
const vendorPaymentLineItemTable = {
  name: "vendorPaymentLineItem",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    vendorPaymentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "vendor_payment_id",
    },
    categoryId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "category_id",
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    sortOrder: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sort_order",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "vendor_payment_line_item",
} as const;
const vendorPaymentTransactionTable = {
  name: "vendorPaymentTransaction",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    vendorPaymentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "vendor_payment_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    transactionDate: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "transaction_date",
    },
    paymentMethod: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "payment_method",
    },
    paymentReference: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "payment_reference",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as "pending" | "approved" | "rejected",
    },
    rejectionReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "rejection_reason",
    },
    reviewedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "reviewed_by",
    },
    reviewedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "reviewed_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "vendor_payment_transaction",
} as const;
const vendorPaymentTransactionAttachmentTable = {
  name: "vendorPaymentTransactionAttachment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    vendorPaymentTransactionId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "vendor_payment_transaction_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as "file" | "url",
    },
    filename: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    objectKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "object_key",
    },
    url: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    mimeType: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "mime_type",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "vendor_payment_transaction_attachment",
} as const;
const vendorPaymentTransactionHistoryTable = {
  name: "vendorPaymentTransactionHistory",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    vendorPaymentTransactionId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "vendor_payment_transaction_id",
    },
    actorId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "actor_id",
    },
    action: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "approved"
        | "rejected"
        | "created"
        | "updated"
        | "submitted"
        | "invoice_submitted"
        | "invoice_updated"
        | "invoice_approved"
        | "invoice_rejected",
    },
    note: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    metadata: {
      type: "json",
      optional: true,
      customType: null as unknown as ReadonlyJSONValue,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "vendor_payment_transaction_history",
} as const;
const verificationTable = {
  name: "verification",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    identifier: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    value: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const whatsappGroupTable = {
  name: "whatsappGroup",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    jid: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "whatsapp_group",
} as const;
const accountRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const advancePaymentAttachmentRelationships = {
  advancePayment: [
    {
      sourceField: ["advancePaymentId"],
      destField: ["id"],
      destSchema: "advancePayment",
      cardinality: "one",
    },
  ],
} as const;
const advancePaymentHistoryRelationships = {
  advancePayment: [
    {
      sourceField: ["advancePaymentId"],
      destField: ["id"],
      destSchema: "advancePayment",
      cardinality: "one",
    },
  ],
  actor: [
    {
      sourceField: ["actorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const advancePaymentLineItemRelationships = {
  advancePayment: [
    {
      sourceField: ["advancePaymentId"],
      destField: ["id"],
      destSchema: "advancePayment",
      cardinality: "one",
    },
  ],
  category: [
    {
      sourceField: ["categoryId"],
      destField: ["id"],
      destSchema: "expenseCategory",
      cardinality: "one",
    },
  ],
} as const;
const advancePaymentRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  reviewer: [
    {
      sourceField: ["reviewedBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  lineItems: [
    {
      sourceField: ["id"],
      destField: ["advancePaymentId"],
      destSchema: "advancePaymentLineItem",
      cardinality: "many",
    },
  ],
  attachments: [
    {
      sourceField: ["id"],
      destField: ["advancePaymentId"],
      destSchema: "advancePaymentAttachment",
      cardinality: "many",
    },
  ],
  history: [
    {
      sourceField: ["id"],
      destField: ["advancePaymentId"],
      destSchema: "advancePaymentHistory",
      cardinality: "many",
    },
  ],
} as const;
const bankAccountRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const eventFeedbackRelationships = {
  event: [
    {
      sourceField: ["eventId"],
      destField: ["id"],
      destSchema: "teamEvent",
      cardinality: "one",
    },
  ],
} as const;
const eventFeedbackSubmissionRelationships = {
  event: [
    {
      sourceField: ["eventId"],
      destField: ["id"],
      destSchema: "teamEvent",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  feedback: [
    {
      sourceField: ["feedbackId"],
      destField: ["id"],
      destSchema: "eventFeedback",
      cardinality: "one",
    },
  ],
} as const;
const eventImmichAlbumRelationships = {
  event: [
    {
      sourceField: ["eventId"],
      destField: ["id"],
      destSchema: "teamEvent",
      cardinality: "one",
    },
  ],
} as const;
const eventInterestRelationships = {
  event: [
    {
      sourceField: ["eventId"],
      destField: ["id"],
      destSchema: "teamEvent",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  reviewer: [
    {
      sourceField: ["reviewedBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const eventPhotoRelationships = {
  event: [
    {
      sourceField: ["eventId"],
      destField: ["id"],
      destSchema: "teamEvent",
      cardinality: "one",
    },
  ],
  uploader: [
    {
      sourceField: ["uploadedBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  reviewer: [
    {
      sourceField: ["reviewedBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const eventReminderSentRelationships = {
  event: [
    {
      sourceField: ["eventId"],
      destField: ["id"],
      destSchema: "teamEvent",
      cardinality: "one",
    },
  ],
} as const;
const eventRsvpPollRelationships = {
  event: [
    {
      sourceField: ["eventId"],
      destField: ["id"],
      destSchema: "teamEvent",
      cardinality: "one",
    },
  ],
  votes: [
    {
      sourceField: ["id"],
      destField: ["pollId"],
      destSchema: "eventRsvpVote",
      cardinality: "many",
    },
  ],
} as const;
const eventRsvpVoteRelationships = {
  poll: [
    {
      sourceField: ["pollId"],
      destField: ["id"],
      destSchema: "eventRsvpPoll",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const eventUpdateRelationships = {
  event: [
    {
      sourceField: ["eventId"],
      destField: ["id"],
      destSchema: "teamEvent",
      cardinality: "one",
    },
  ],
  author: [
    {
      sourceField: ["createdBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  reviewer: [
    {
      sourceField: ["reviewedBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const notificationTopicPreferenceRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const reimbursementAttachmentRelationships = {
  reimbursement: [
    {
      sourceField: ["reimbursementId"],
      destField: ["id"],
      destSchema: "reimbursement",
      cardinality: "one",
    },
  ],
} as const;
const reimbursementHistoryRelationships = {
  reimbursement: [
    {
      sourceField: ["reimbursementId"],
      destField: ["id"],
      destSchema: "reimbursement",
      cardinality: "one",
    },
  ],
  actor: [
    {
      sourceField: ["actorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const reimbursementLineItemRelationships = {
  reimbursement: [
    {
      sourceField: ["reimbursementId"],
      destField: ["id"],
      destSchema: "reimbursement",
      cardinality: "one",
    },
  ],
  category: [
    {
      sourceField: ["categoryId"],
      destField: ["id"],
      destSchema: "expenseCategory",
      cardinality: "one",
    },
  ],
  voucherAttachment: [
    {
      sourceField: ["voucherAttachmentId"],
      destField: ["id"],
      destSchema: "reimbursementAttachment",
      cardinality: "one",
    },
  ],
} as const;
const reimbursementRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  reviewer: [
    {
      sourceField: ["reviewedBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  event: [
    {
      sourceField: ["eventId"],
      destField: ["id"],
      destSchema: "teamEvent",
      cardinality: "one",
    },
  ],
  lineItems: [
    {
      sourceField: ["id"],
      destField: ["reimbursementId"],
      destSchema: "reimbursementLineItem",
      cardinality: "many",
    },
  ],
  attachments: [
    {
      sourceField: ["id"],
      destField: ["reimbursementId"],
      destSchema: "reimbursementAttachment",
      cardinality: "many",
    },
  ],
  history: [
    {
      sourceField: ["id"],
      destField: ["reimbursementId"],
      destSchema: "reimbursementHistory",
      cardinality: "many",
    },
  ],
} as const;
const rolePermissionRelationships = {
  role: [
    {
      sourceField: ["roleId"],
      destField: ["id"],
      destSchema: "role",
      cardinality: "one",
    },
  ],
  permission: [
    {
      sourceField: ["permissionId"],
      destField: ["id"],
      destSchema: "permission",
      cardinality: "one",
    },
  ],
} as const;
const roleRelationships = {
  permissions: [
    {
      sourceField: ["id"],
      destField: ["roleId"],
      destSchema: "rolePermission",
      cardinality: "many",
    },
  ],
} as const;
const scheduledMessageRecipientRelationships = {
  scheduledMessage: [
    {
      sourceField: ["scheduledMessageId"],
      destField: ["id"],
      destSchema: "scheduledMessage",
      cardinality: "one",
    },
  ],
} as const;
const scheduledMessageRelationships = {
  creator: [
    {
      sourceField: ["createdBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  recipients: [
    {
      sourceField: ["id"],
      destField: ["scheduledMessageId"],
      destSchema: "scheduledMessageRecipient",
      cardinality: "many",
    },
  ],
} as const;
const sessionRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const teamEventMemberRelationships = {
  event: [
    {
      sourceField: ["eventId"],
      destField: ["id"],
      destSchema: "teamEvent",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const teamEventRelationships = {
  team: [
    {
      sourceField: ["teamId"],
      destField: ["id"],
      destSchema: "team",
      cardinality: "one",
    },
  ],
  whatsappGroup: [
    {
      sourceField: ["whatsappGroupId"],
      destField: ["id"],
      destSchema: "whatsappGroup",
      cardinality: "one",
    },
  ],
  series: [
    {
      sourceField: ["seriesId"],
      destField: ["id"],
      destSchema: "teamEvent",
      cardinality: "one",
    },
  ],
  exceptions: [
    {
      sourceField: ["id"],
      destField: ["seriesId"],
      destSchema: "teamEvent",
      cardinality: "many",
    },
  ],
  members: [
    {
      sourceField: ["id"],
      destField: ["eventId"],
      destSchema: "teamEventMember",
      cardinality: "many",
    },
  ],
  interests: [
    {
      sourceField: ["id"],
      destField: ["eventId"],
      destSchema: "eventInterest",
      cardinality: "many",
    },
  ],
  feedback: [
    {
      sourceField: ["id"],
      destField: ["eventId"],
      destSchema: "eventFeedback",
      cardinality: "many",
    },
  ],
  creator: [
    {
      sourceField: ["createdBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  reimbursements: [
    {
      sourceField: ["id"],
      destField: ["eventId"],
      destSchema: "reimbursement",
      cardinality: "many",
    },
  ],
  vendorPayments: [
    {
      sourceField: ["id"],
      destField: ["eventId"],
      destSchema: "vendorPayment",
      cardinality: "many",
    },
  ],
} as const;
const teamMemberRelationships = {
  team: [
    {
      sourceField: ["teamId"],
      destField: ["id"],
      destSchema: "team",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const teamRelationships = {
  whatsappGroup: [
    {
      sourceField: ["whatsappGroupId"],
      destField: ["id"],
      destSchema: "whatsappGroup",
      cardinality: "one",
    },
  ],
  members: [
    {
      sourceField: ["id"],
      destField: ["teamId"],
      destSchema: "teamMember",
      cardinality: "many",
    },
  ],
  events: [
    {
      sourceField: ["id"],
      destField: ["teamId"],
      destSchema: "teamEvent",
      cardinality: "many",
    },
  ],
} as const;
const userRelationships = {
  sessions: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "session",
      cardinality: "many",
    },
  ],
  accounts: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "account",
      cardinality: "many",
    },
  ],
  notificationTopicPreferences: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "notificationTopicPreference",
      cardinality: "many",
    },
  ],
  roleRef: [
    {
      sourceField: ["role"],
      destField: ["id"],
      destSchema: "role",
      cardinality: "one",
    },
  ],
} as const;
const vendorPaymentAttachmentRelationships = {
  vendorPayment: [
    {
      sourceField: ["vendorPaymentId"],
      destField: ["id"],
      destSchema: "vendorPayment",
      cardinality: "one",
    },
  ],
} as const;
const vendorPaymentHistoryRelationships = {
  vendorPayment: [
    {
      sourceField: ["vendorPaymentId"],
      destField: ["id"],
      destSchema: "vendorPayment",
      cardinality: "one",
    },
  ],
  actor: [
    {
      sourceField: ["actorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const vendorPaymentLineItemRelationships = {
  vendorPayment: [
    {
      sourceField: ["vendorPaymentId"],
      destField: ["id"],
      destSchema: "vendorPayment",
      cardinality: "one",
    },
  ],
  category: [
    {
      sourceField: ["categoryId"],
      destField: ["id"],
      destSchema: "expenseCategory",
      cardinality: "one",
    },
  ],
} as const;
const vendorPaymentRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  vendor: [
    {
      sourceField: ["vendorId"],
      destField: ["id"],
      destSchema: "vendor",
      cardinality: "one",
    },
  ],
  reviewer: [
    {
      sourceField: ["reviewedBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  invoiceReviewer: [
    {
      sourceField: ["invoiceReviewedBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  event: [
    {
      sourceField: ["eventId"],
      destField: ["id"],
      destSchema: "teamEvent",
      cardinality: "one",
    },
  ],
  lineItems: [
    {
      sourceField: ["id"],
      destField: ["vendorPaymentId"],
      destSchema: "vendorPaymentLineItem",
      cardinality: "many",
    },
  ],
  attachments: [
    {
      sourceField: ["id"],
      destField: ["vendorPaymentId"],
      destSchema: "vendorPaymentAttachment",
      cardinality: "many",
    },
  ],
  history: [
    {
      sourceField: ["id"],
      destField: ["vendorPaymentId"],
      destSchema: "vendorPaymentHistory",
      cardinality: "many",
    },
  ],
  transactions: [
    {
      sourceField: ["id"],
      destField: ["vendorPaymentId"],
      destSchema: "vendorPaymentTransaction",
      cardinality: "many",
    },
  ],
} as const;
const vendorPaymentTransactionAttachmentRelationships = {
  transaction: [
    {
      sourceField: ["vendorPaymentTransactionId"],
      destField: ["id"],
      destSchema: "vendorPaymentTransaction",
      cardinality: "one",
    },
  ],
} as const;
const vendorPaymentTransactionHistoryRelationships = {
  transaction: [
    {
      sourceField: ["vendorPaymentTransactionId"],
      destField: ["id"],
      destSchema: "vendorPaymentTransaction",
      cardinality: "one",
    },
  ],
  actor: [
    {
      sourceField: ["actorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const vendorPaymentTransactionRelationships = {
  vendorPayment: [
    {
      sourceField: ["vendorPaymentId"],
      destField: ["id"],
      destSchema: "vendorPayment",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  reviewer: [
    {
      sourceField: ["reviewedBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  attachments: [
    {
      sourceField: ["id"],
      destField: ["vendorPaymentTransactionId"],
      destSchema: "vendorPaymentTransactionAttachment",
      cardinality: "many",
    },
  ],
  history: [
    {
      sourceField: ["id"],
      destField: ["vendorPaymentTransactionId"],
      destSchema: "vendorPaymentTransactionHistory",
      cardinality: "many",
    },
  ],
} as const;
const vendorRelationships = {
  creator: [
    {
      sourceField: ["createdBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  vendorPayments: [
    {
      sourceField: ["id"],
      destField: ["vendorId"],
      destSchema: "vendorPayment",
      cardinality: "many",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    account: accountTable,
    advancePayment: advancePaymentTable,
    advancePaymentAttachment: advancePaymentAttachmentTable,
    advancePaymentHistory: advancePaymentHistoryTable,
    advancePaymentLineItem: advancePaymentLineItemTable,
    appConfig: appConfigTable,
    bankAccount: bankAccountTable,
    eventFeedback: eventFeedbackTable,
    eventFeedbackSubmission: eventFeedbackSubmissionTable,
    eventImmichAlbum: eventImmichAlbumTable,
    eventInterest: eventInterestTable,
    eventPhoto: eventPhotoTable,
    eventReminderSent: eventReminderSentTable,
    eventRsvpPoll: eventRsvpPollTable,
    eventRsvpVote: eventRsvpVoteTable,
    eventUpdate: eventUpdateTable,
    expenseCategory: expenseCategoryTable,
    notificationTopicPreference: notificationTopicPreferenceTable,
    permission: permissionTable,
    reimbursement: reimbursementTable,
    reimbursementAttachment: reimbursementAttachmentTable,
    reimbursementHistory: reimbursementHistoryTable,
    reimbursementLineItem: reimbursementLineItemTable,
    role: roleTable,
    rolePermission: rolePermissionTable,
    scheduledMessage: scheduledMessageTable,
    scheduledMessageRecipient: scheduledMessageRecipientTable,
    session: sessionTable,
    team: teamTable,
    teamEvent: teamEventTable,
    teamEventMember: teamEventMemberTable,
    teamMember: teamMemberTable,
    user: userTable,
    vendor: vendorTable,
    vendorPayment: vendorPaymentTable,
    vendorPaymentAttachment: vendorPaymentAttachmentTable,
    vendorPaymentHistory: vendorPaymentHistoryTable,
    vendorPaymentLineItem: vendorPaymentLineItemTable,
    vendorPaymentTransaction: vendorPaymentTransactionTable,
    vendorPaymentTransactionAttachment: vendorPaymentTransactionAttachmentTable,
    vendorPaymentTransactionHistory: vendorPaymentTransactionHistoryTable,
    verification: verificationTable,
    whatsappGroup: whatsappGroupTable,
  },
  relationships: {
    account: accountRelationships,
    advancePaymentAttachment: advancePaymentAttachmentRelationships,
    advancePaymentHistory: advancePaymentHistoryRelationships,
    advancePaymentLineItem: advancePaymentLineItemRelationships,
    advancePayment: advancePaymentRelationships,
    bankAccount: bankAccountRelationships,
    eventFeedback: eventFeedbackRelationships,
    eventFeedbackSubmission: eventFeedbackSubmissionRelationships,
    eventImmichAlbum: eventImmichAlbumRelationships,
    eventInterest: eventInterestRelationships,
    eventPhoto: eventPhotoRelationships,
    eventReminderSent: eventReminderSentRelationships,
    eventRsvpPoll: eventRsvpPollRelationships,
    eventRsvpVote: eventRsvpVoteRelationships,
    eventUpdate: eventUpdateRelationships,
    notificationTopicPreference: notificationTopicPreferenceRelationships,
    reimbursementAttachment: reimbursementAttachmentRelationships,
    reimbursementHistory: reimbursementHistoryRelationships,
    reimbursementLineItem: reimbursementLineItemRelationships,
    reimbursement: reimbursementRelationships,
    rolePermission: rolePermissionRelationships,
    role: roleRelationships,
    scheduledMessageRecipient: scheduledMessageRecipientRelationships,
    scheduledMessage: scheduledMessageRelationships,
    session: sessionRelationships,
    teamEventMember: teamEventMemberRelationships,
    teamEvent: teamEventRelationships,
    teamMember: teamMemberRelationships,
    team: teamRelationships,
    user: userRelationships,
    vendorPaymentAttachment: vendorPaymentAttachmentRelationships,
    vendorPaymentHistory: vendorPaymentHistoryRelationships,
    vendorPaymentLineItem: vendorPaymentLineItemRelationships,
    vendorPayment: vendorPaymentRelationships,
    vendorPaymentTransactionAttachment:
      vendorPaymentTransactionAttachmentRelationships,
    vendorPaymentTransactionHistory:
      vendorPaymentTransactionHistoryRelationships,
    vendorPaymentTransaction: vendorPaymentTransactionRelationships,
    vendor: vendorRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "account" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Account = Row<(typeof schema)["tables"]["account"]>;
/**
 * Represents a row from the "advancePayment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AdvancePayment = Row<(typeof schema)["tables"]["advancePayment"]>;
/**
 * Represents a row from the "advancePaymentAttachment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AdvancePaymentAttachment = Row<
  (typeof schema)["tables"]["advancePaymentAttachment"]
>;
/**
 * Represents a row from the "advancePaymentHistory" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AdvancePaymentHistory = Row<
  (typeof schema)["tables"]["advancePaymentHistory"]
>;
/**
 * Represents a row from the "advancePaymentLineItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AdvancePaymentLineItem = Row<
  (typeof schema)["tables"]["advancePaymentLineItem"]
>;
/**
 * Represents a row from the "appConfig" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AppConfig = Row<(typeof schema)["tables"]["appConfig"]>;
/**
 * Represents a row from the "bankAccount" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type BankAccount = Row<(typeof schema)["tables"]["bankAccount"]>;
/**
 * Represents a row from the "eventFeedback" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EventFeedback = Row<(typeof schema)["tables"]["eventFeedback"]>;
/**
 * Represents a row from the "eventFeedbackSubmission" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EventFeedbackSubmission = Row<
  (typeof schema)["tables"]["eventFeedbackSubmission"]
>;
/**
 * Represents a row from the "eventImmichAlbum" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EventImmichAlbum = Row<
  (typeof schema)["tables"]["eventImmichAlbum"]
>;
/**
 * Represents a row from the "eventInterest" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EventInterest = Row<(typeof schema)["tables"]["eventInterest"]>;
/**
 * Represents a row from the "eventPhoto" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EventPhoto = Row<(typeof schema)["tables"]["eventPhoto"]>;
/**
 * Represents a row from the "eventReminderSent" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EventReminderSent = Row<
  (typeof schema)["tables"]["eventReminderSent"]
>;
/**
 * Represents a row from the "eventRsvpPoll" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EventRsvpPoll = Row<(typeof schema)["tables"]["eventRsvpPoll"]>;
/**
 * Represents a row from the "eventRsvpVote" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EventRsvpVote = Row<(typeof schema)["tables"]["eventRsvpVote"]>;
/**
 * Represents a row from the "eventUpdate" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EventUpdate = Row<(typeof schema)["tables"]["eventUpdate"]>;
/**
 * Represents a row from the "expenseCategory" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ExpenseCategory = Row<(typeof schema)["tables"]["expenseCategory"]>;
/**
 * Represents a row from the "notificationTopicPreference" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type NotificationTopicPreference = Row<
  (typeof schema)["tables"]["notificationTopicPreference"]
>;
/**
 * Represents a row from the "permission" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Permission = Row<(typeof schema)["tables"]["permission"]>;
/**
 * Represents a row from the "reimbursement" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Reimbursement = Row<(typeof schema)["tables"]["reimbursement"]>;
/**
 * Represents a row from the "reimbursementAttachment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ReimbursementAttachment = Row<
  (typeof schema)["tables"]["reimbursementAttachment"]
>;
/**
 * Represents a row from the "reimbursementHistory" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ReimbursementHistory = Row<
  (typeof schema)["tables"]["reimbursementHistory"]
>;
/**
 * Represents a row from the "reimbursementLineItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ReimbursementLineItem = Row<
  (typeof schema)["tables"]["reimbursementLineItem"]
>;
/**
 * Represents a row from the "role" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Role = Row<(typeof schema)["tables"]["role"]>;
/**
 * Represents a row from the "rolePermission" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RolePermission = Row<(typeof schema)["tables"]["rolePermission"]>;
/**
 * Represents a row from the "scheduledMessage" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ScheduledMessage = Row<
  (typeof schema)["tables"]["scheduledMessage"]
>;
/**
 * Represents a row from the "scheduledMessageRecipient" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ScheduledMessageRecipient = Row<
  (typeof schema)["tables"]["scheduledMessageRecipient"]
>;
/**
 * Represents a row from the "session" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Session = Row<(typeof schema)["tables"]["session"]>;
/**
 * Represents a row from the "team" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Team = Row<(typeof schema)["tables"]["team"]>;
/**
 * Represents a row from the "teamEvent" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TeamEvent = Row<(typeof schema)["tables"]["teamEvent"]>;
/**
 * Represents a row from the "teamEventMember" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TeamEventMember = Row<(typeof schema)["tables"]["teamEventMember"]>;
/**
 * Represents a row from the "teamMember" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TeamMember = Row<(typeof schema)["tables"]["teamMember"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;
/**
 * Represents a row from the "vendor" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Vendor = Row<(typeof schema)["tables"]["vendor"]>;
/**
 * Represents a row from the "vendorPayment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type VendorPayment = Row<(typeof schema)["tables"]["vendorPayment"]>;
/**
 * Represents a row from the "vendorPaymentAttachment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type VendorPaymentAttachment = Row<
  (typeof schema)["tables"]["vendorPaymentAttachment"]
>;
/**
 * Represents a row from the "vendorPaymentHistory" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type VendorPaymentHistory = Row<
  (typeof schema)["tables"]["vendorPaymentHistory"]
>;
/**
 * Represents a row from the "vendorPaymentLineItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type VendorPaymentLineItem = Row<
  (typeof schema)["tables"]["vendorPaymentLineItem"]
>;
/**
 * Represents a row from the "vendorPaymentTransaction" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type VendorPaymentTransaction = Row<
  (typeof schema)["tables"]["vendorPaymentTransaction"]
>;
/**
 * Represents a row from the "vendorPaymentTransactionAttachment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type VendorPaymentTransactionAttachment = Row<
  (typeof schema)["tables"]["vendorPaymentTransactionAttachment"]
>;
/**
 * Represents a row from the "vendorPaymentTransactionHistory" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type VendorPaymentTransactionHistory = Row<
  (typeof schema)["tables"]["vendorPaymentTransactionHistory"]
>;
/**
 * Represents a row from the "verification" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Verification = Row<(typeof schema)["tables"]["verification"]>;
/**
 * Represents a row from the "whatsappGroup" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type WhatsappGroup = Row<(typeof schema)["tables"]["whatsappGroup"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
