// @generated drizzle-zero signature:sha256:2887f2a9ee8c3c333b7cb621c4ec0f4a643bda4914bbd595ab9fa932d79d91e9
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { ReadonlyJSONValue, Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const accountTable = {
  name: "account",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    accountId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "account_id",
    },
    providerId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    accessToken: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "access_token",
    },
    refreshToken: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "refresh_token",
    },
    idToken: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "id_token",
    },
    accessTokenExpiresAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "access_token_expires_at",
    },
    refreshTokenExpiresAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "refresh_token_expires_at",
    },
    scope: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    password: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const advancePaymentTable = {
  name: "advancePayment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    city: {
      type: "string",
      optional: true,
      customType: null as unknown as "bangalore" | "mumbai",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "draft"
        | "pending"
        | "approved"
        | "rejected",
    },
    rejectionReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "rejection_reason",
    },
    bankAccountName: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_account_name",
    },
    bankAccountNumber: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_account_number",
    },
    bankAccountIfscCode: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_account_ifsc_code",
    },
    reviewedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "reviewed_by",
    },
    reviewedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "reviewed_at",
    },
    submittedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "submitted_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "advance_payment",
} as const;
const advancePaymentAttachmentTable = {
  name: "advancePaymentAttachment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    advancePaymentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "advance_payment_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as "file" | "url",
    },
    filename: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    objectKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "object_key",
    },
    url: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    mimeType: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "mime_type",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "advance_payment_attachment",
} as const;
const advancePaymentHistoryTable = {
  name: "advancePaymentHistory",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    advancePaymentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "advance_payment_id",
    },
    actorId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "actor_id",
    },
    action: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "approved"
        | "rejected"
        | "created"
        | "updated"
        | "submitted",
    },
    note: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    metadata: {
      type: "json",
      optional: true,
      customType: null as unknown as ReadonlyJSONValue,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "advance_payment_history",
} as const;
const advancePaymentLineItemTable = {
  name: "advancePaymentLineItem",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    advancePaymentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "advance_payment_id",
    },
    categoryId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "category_id",
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    sortOrder: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sort_order",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "advance_payment_line_item",
} as const;
const appConfigTable = {
  name: "appConfig",
  columns: {
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    value: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["key"],
  serverName: "app_config",
} as const;
const bankAccountTable = {
  name: "bankAccount",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    accountName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "account_name",
    },
    accountNumber: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "account_number",
    },
    ifscCode: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "ifsc_code",
    },
    isDefault: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_default",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "bank_account",
} as const;
const expenseCategoryTable = {
  name: "expenseCategory",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "expense_category",
} as const;
const reimbursementTable = {
  name: "reimbursement",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    city: {
      type: "string",
      optional: true,
      customType: null as unknown as "bangalore" | "mumbai",
    },
    expenseDate: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "expense_date",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "draft"
        | "pending"
        | "approved"
        | "rejected",
    },
    rejectionReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "rejection_reason",
    },
    bankAccountName: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_account_name",
    },
    bankAccountNumber: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_account_number",
    },
    bankAccountIfscCode: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_account_ifsc_code",
    },
    reviewedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "reviewed_by",
    },
    reviewedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "reviewed_at",
    },
    submittedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "submitted_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const reimbursementAttachmentTable = {
  name: "reimbursementAttachment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    reimbursementId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "reimbursement_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as "file" | "url",
    },
    filename: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    objectKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "object_key",
    },
    url: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    mimeType: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "mime_type",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "reimbursement_attachment",
} as const;
const reimbursementHistoryTable = {
  name: "reimbursementHistory",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    reimbursementId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "reimbursement_id",
    },
    actorId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "actor_id",
    },
    action: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "approved"
        | "rejected"
        | "created"
        | "updated"
        | "submitted",
    },
    note: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    metadata: {
      type: "json",
      optional: true,
      customType: null as unknown as ReadonlyJSONValue,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "reimbursement_history",
} as const;
const reimbursementLineItemTable = {
  name: "reimbursementLineItem",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    reimbursementId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "reimbursement_id",
    },
    categoryId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "category_id",
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    sortOrder: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sort_order",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "reimbursement_line_item",
} as const;
const sessionTable = {
  name: "session",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    token: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    ipAddress: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "ip_address",
    },
    userAgent: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "user_agent",
    },
    impersonatedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "impersonated_by",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
  },
  primaryKey: ["id"],
} as const;
const teamTable = {
  name: "team",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    whatsappGroupId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "whatsapp_group_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const teamMemberTable = {
  name: "teamMember",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    teamId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "team_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as "member" | "lead",
    },
    joinedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "joined_at",
    },
  },
  primaryKey: ["id"],
  serverName: "team_member",
} as const;
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    emailVerified: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "email_verified",
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    gender: {
      type: "string",
      optional: true,
      customType: null as unknown as "male" | "female",
    },
    dob: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    phone: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    isOnWhatsapp: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_on_whatsapp",
    },
    whatsappNotifications: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "whatsapp_notifications",
    },
    isActive: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_active",
    },
    attendedOrientation: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "attended_orientation",
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as "volunteer" | "admin",
    },
    banned: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    banReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "ban_reason",
    },
    banExpires: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "ban_expires",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const verificationTable = {
  name: "verification",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    identifier: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    value: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const whatsappGroupTable = {
  name: "whatsappGroup",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    jid: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "whatsapp_group",
} as const;
const accountRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const advancePaymentAttachmentRelationships = {
  advancePayment: [
    {
      sourceField: ["advancePaymentId"],
      destField: ["id"],
      destSchema: "advancePayment",
      cardinality: "one",
    },
  ],
} as const;
const advancePaymentHistoryRelationships = {
  advancePayment: [
    {
      sourceField: ["advancePaymentId"],
      destField: ["id"],
      destSchema: "advancePayment",
      cardinality: "one",
    },
  ],
  actor: [
    {
      sourceField: ["actorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const advancePaymentLineItemRelationships = {
  advancePayment: [
    {
      sourceField: ["advancePaymentId"],
      destField: ["id"],
      destSchema: "advancePayment",
      cardinality: "one",
    },
  ],
  category: [
    {
      sourceField: ["categoryId"],
      destField: ["id"],
      destSchema: "expenseCategory",
      cardinality: "one",
    },
  ],
} as const;
const advancePaymentRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  reviewer: [
    {
      sourceField: ["reviewedBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  lineItems: [
    {
      sourceField: ["id"],
      destField: ["advancePaymentId"],
      destSchema: "advancePaymentLineItem",
      cardinality: "many",
    },
  ],
  attachments: [
    {
      sourceField: ["id"],
      destField: ["advancePaymentId"],
      destSchema: "advancePaymentAttachment",
      cardinality: "many",
    },
  ],
  history: [
    {
      sourceField: ["id"],
      destField: ["advancePaymentId"],
      destSchema: "advancePaymentHistory",
      cardinality: "many",
    },
  ],
} as const;
const bankAccountRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const reimbursementAttachmentRelationships = {
  reimbursement: [
    {
      sourceField: ["reimbursementId"],
      destField: ["id"],
      destSchema: "reimbursement",
      cardinality: "one",
    },
  ],
} as const;
const reimbursementHistoryRelationships = {
  reimbursement: [
    {
      sourceField: ["reimbursementId"],
      destField: ["id"],
      destSchema: "reimbursement",
      cardinality: "one",
    },
  ],
  actor: [
    {
      sourceField: ["actorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const reimbursementLineItemRelationships = {
  reimbursement: [
    {
      sourceField: ["reimbursementId"],
      destField: ["id"],
      destSchema: "reimbursement",
      cardinality: "one",
    },
  ],
  category: [
    {
      sourceField: ["categoryId"],
      destField: ["id"],
      destSchema: "expenseCategory",
      cardinality: "one",
    },
  ],
} as const;
const reimbursementRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  reviewer: [
    {
      sourceField: ["reviewedBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  lineItems: [
    {
      sourceField: ["id"],
      destField: ["reimbursementId"],
      destSchema: "reimbursementLineItem",
      cardinality: "many",
    },
  ],
  attachments: [
    {
      sourceField: ["id"],
      destField: ["reimbursementId"],
      destSchema: "reimbursementAttachment",
      cardinality: "many",
    },
  ],
  history: [
    {
      sourceField: ["id"],
      destField: ["reimbursementId"],
      destSchema: "reimbursementHistory",
      cardinality: "many",
    },
  ],
} as const;
const sessionRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const teamMemberRelationships = {
  team: [
    {
      sourceField: ["teamId"],
      destField: ["id"],
      destSchema: "team",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const teamRelationships = {
  whatsappGroup: [
    {
      sourceField: ["whatsappGroupId"],
      destField: ["id"],
      destSchema: "whatsappGroup",
      cardinality: "one",
    },
  ],
  members: [
    {
      sourceField: ["id"],
      destField: ["teamId"],
      destSchema: "teamMember",
      cardinality: "many",
    },
  ],
} as const;
const userRelationships = {
  sessions: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "session",
      cardinality: "many",
    },
  ],
  accounts: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "account",
      cardinality: "many",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    account: accountTable,
    advancePayment: advancePaymentTable,
    advancePaymentAttachment: advancePaymentAttachmentTable,
    advancePaymentHistory: advancePaymentHistoryTable,
    advancePaymentLineItem: advancePaymentLineItemTable,
    appConfig: appConfigTable,
    bankAccount: bankAccountTable,
    expenseCategory: expenseCategoryTable,
    reimbursement: reimbursementTable,
    reimbursementAttachment: reimbursementAttachmentTable,
    reimbursementHistory: reimbursementHistoryTable,
    reimbursementLineItem: reimbursementLineItemTable,
    session: sessionTable,
    team: teamTable,
    teamMember: teamMemberTable,
    user: userTable,
    verification: verificationTable,
    whatsappGroup: whatsappGroupTable,
  },
  relationships: {
    account: accountRelationships,
    advancePaymentAttachment: advancePaymentAttachmentRelationships,
    advancePaymentHistory: advancePaymentHistoryRelationships,
    advancePaymentLineItem: advancePaymentLineItemRelationships,
    advancePayment: advancePaymentRelationships,
    bankAccount: bankAccountRelationships,
    reimbursementAttachment: reimbursementAttachmentRelationships,
    reimbursementHistory: reimbursementHistoryRelationships,
    reimbursementLineItem: reimbursementLineItemRelationships,
    reimbursement: reimbursementRelationships,
    session: sessionRelationships,
    teamMember: teamMemberRelationships,
    team: teamRelationships,
    user: userRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "account" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Account = Row<(typeof schema)["tables"]["account"]>;
/**
 * Represents a row from the "advancePayment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AdvancePayment = Row<(typeof schema)["tables"]["advancePayment"]>;
/**
 * Represents a row from the "advancePaymentAttachment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AdvancePaymentAttachment = Row<
  (typeof schema)["tables"]["advancePaymentAttachment"]
>;
/**
 * Represents a row from the "advancePaymentHistory" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AdvancePaymentHistory = Row<
  (typeof schema)["tables"]["advancePaymentHistory"]
>;
/**
 * Represents a row from the "advancePaymentLineItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AdvancePaymentLineItem = Row<
  (typeof schema)["tables"]["advancePaymentLineItem"]
>;
/**
 * Represents a row from the "appConfig" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AppConfig = Row<(typeof schema)["tables"]["appConfig"]>;
/**
 * Represents a row from the "bankAccount" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type BankAccount = Row<(typeof schema)["tables"]["bankAccount"]>;
/**
 * Represents a row from the "expenseCategory" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ExpenseCategory = Row<(typeof schema)["tables"]["expenseCategory"]>;
/**
 * Represents a row from the "reimbursement" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Reimbursement = Row<(typeof schema)["tables"]["reimbursement"]>;
/**
 * Represents a row from the "reimbursementAttachment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ReimbursementAttachment = Row<
  (typeof schema)["tables"]["reimbursementAttachment"]
>;
/**
 * Represents a row from the "reimbursementHistory" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ReimbursementHistory = Row<
  (typeof schema)["tables"]["reimbursementHistory"]
>;
/**
 * Represents a row from the "reimbursementLineItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ReimbursementLineItem = Row<
  (typeof schema)["tables"]["reimbursementLineItem"]
>;
/**
 * Represents a row from the "session" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Session = Row<(typeof schema)["tables"]["session"]>;
/**
 * Represents a row from the "team" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Team = Row<(typeof schema)["tables"]["team"]>;
/**
 * Represents a row from the "teamMember" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TeamMember = Row<(typeof schema)["tables"]["teamMember"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;
/**
 * Represents a row from the "verification" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Verification = Row<(typeof schema)["tables"]["verification"]>;
/**
 * Represents a row from the "whatsappGroup" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type WhatsappGroup = Row<(typeof schema)["tables"]["whatsappGroup"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
