import { expect, test } from "../../fixtures/test";

test("slow Jobs polls do not overlap", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "super_admin", "Admin-only test");
  await page.goto("/jobs");
  await expect(page.getByRole("heading", { name: "Jobs" })).toBeVisible();
  await page.clock.install();
  let requests = 0;
  let release = () => {};
  const pending = new Promise<void>((resolve) => {
    release = resolve;
  });
  await page.route("**/api/jobs?*", async (route) => {
    requests += 1;
    await pending;
    await route.fulfill({ json: { jobs: [], total: 0 } });
  });
  try {
    await page.getByRole("button", { name: "Refresh", exact: true }).click();
    await expect.poll(() => requests).toBe(1);
    await page.clock.fastForward(10_000);
    await page.clock.fastForward(10_000);
    // Let network events generated by the timer reach the request handler.
    await page.waitForTimeout(100);
    expect(requests).toBe(1);
    const response = page.waitForResponse(
      (result) => new URL(result.url()).pathname === "/api/jobs"
    );
    release();
    await response;
    await page.waitForTimeout(100);
    await page.clock.fastForward(10_000);
    await expect.poll(() => requests).toBe(2);
  } finally {
    release();
    await page.unrouteAll({ behavior: "wait" });
  }
});

test.describe("Jobs dashboard (admin)", () => {
  test.beforeEach(async ({ page }, testInfo) => {
    test.skip(testInfo.project.name !== "super_admin", "Admin-only test");

    await page.goto("/jobs");
    await expect(page.getByRole("heading", { name: "Jobs" })).toBeVisible({
      timeout: 10_000,
    });
  });

  test("renders jobs page with heading", async ({ page }) => {
    await expect(page.getByRole("heading", { name: "Jobs" })).toBeVisible();
  });

  test("renders stats cards", async ({ page }) => {
    // Stats cards may show 0 but should still render
    await expect(page.locator("[data-slot='card-title']").first()).toBeVisible({
      timeout: 10_000,
    });
  });

  test("state filter dropdown is present", async ({ page }) => {
    await expect(page.getByRole("button", { name: "Add filter" })).toBeVisible({
      timeout: 5000,
    });
  });

  test("refresh button is visible", async ({ page }) => {
    // Refresh icon button exists
    const refreshBtn = page.getByRole("button", { name: /Refresh/i });
    await expect(refreshBtn).toBeVisible({ timeout: 5000 });
  });
});

test.describe("Jobs route guard (volunteer)", () => {
  test("volunteer redirected from /jobs to dashboard", async ({
    page,
  }, testInfo) => {
    test.skip(testInfo.project.name !== "volunteer", "Volunteer-only test");

    await page.goto("/jobs");
    await page.waitForURL("/", { timeout: 10_000 });
    await expect(
      page.getByRole("heading", { name: "Dashboard" })
    ).toBeVisible();
  });
});
