/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppExportRouteImport } from './routes/_app/export'
import { Route as AppTeamsRouteRouteImport } from './routes/_app/teams/route'
import { Route as AppReimbursementsRouteRouteImport } from './routes/_app/reimbursements/route'
import { Route as AppEventsRouteRouteImport } from './routes/_app/events/route'
import { Route as AppAdvancePaymentsRouteRouteImport } from './routes/_app/advance-payments/route'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AppReimbursementsIndexRouteImport } from './routes/_app/reimbursements/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppAdvancePaymentsIndexRouteImport } from './routes/_app/advance-payments/index'
import { Route as ApiZeroQueryRouteImport } from './routes/api/zero/query'
import { Route as ApiZeroMutateRouteImport } from './routes/api/zero/mutate'
import { Route as ApiLogIngestRouteImport } from './routes/api/log/ingest'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAttachmentsDownloadRouteImport } from './routes/api/attachments/download'
import { Route as AppTeamsIdRouteImport } from './routes/_app/teams/$id'
import { Route as AppReimbursementsNewRouteImport } from './routes/_app/reimbursements/new'
import { Route as AppReimbursementsIdRouteImport } from './routes/_app/reimbursements/$id'
import { Route as AppEventsIdRouteImport } from './routes/_app/events/$id'
import { Route as AppAdvancePaymentsNewRouteImport } from './routes/_app/advance-payments/new'
import { Route as AppAdvancePaymentsIdRouteImport } from './routes/_app/advance-payments/$id'
import { Route as ApiImmichThumbnailIdRouteImport } from './routes/api/immich/thumbnail.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRouteRoute = AppTeamsRouteRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppReimbursementsRouteRoute = AppReimbursementsRouteRouteImport.update({
  id: '/reimbursements',
  path: '/reimbursements',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRouteRoute = AppEventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvancePaymentsRouteRoute = AppAdvancePaymentsRouteRouteImport.update({
  id: '/advance-payments',
  path: '/advance-payments',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeamsRouteRoute,
} as any)
const AppReimbursementsIndexRoute = AppReimbursementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReimbursementsRouteRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventsRouteRoute,
} as any)
const AppAdvancePaymentsIndexRoute = AppAdvancePaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdvancePaymentsRouteRoute,
} as any)
const ApiZeroQueryRoute = ApiZeroQueryRouteImport.update({
  id: '/api/zero/query',
  path: '/api/zero/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeroMutateRoute = ApiZeroMutateRouteImport.update({
  id: '/api/zero/mutate',
  path: '/api/zero/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogIngestRoute = ApiLogIngestRouteImport.update({
  id: '/api/log/ingest',
  path: '/api/log/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsDownloadRoute = ApiAttachmentsDownloadRouteImport.update({
  id: '/api/attachments/download',
  path: '/api/attachments/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamsIdRoute = AppTeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTeamsRouteRoute,
} as any)
const AppReimbursementsNewRoute = AppReimbursementsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppReimbursementsRouteRoute,
} as any)
const AppReimbursementsIdRoute = AppReimbursementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReimbursementsRouteRoute,
} as any)
const AppEventsIdRoute = AppEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEventsRouteRoute,
} as any)
const AppAdvancePaymentsNewRoute = AppAdvancePaymentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAdvancePaymentsRouteRoute,
} as any)
const AppAdvancePaymentsIdRoute = AppAdvancePaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdvancePaymentsRouteRoute,
} as any)
const ApiImmichThumbnailIdRoute = ApiImmichThumbnailIdRouteImport.update({
  id: '/api/immich/thumbnail/$id',
  path: '/api/immich/thumbnail/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/advance-payments': typeof AppAdvancePaymentsRouteRouteWithChildren
  '/events': typeof AppEventsRouteRouteWithChildren
  '/reimbursements': typeof AppReimbursementsRouteRouteWithChildren
  '/teams': typeof AppTeamsRouteRouteWithChildren
  '/export': typeof AppExportRoute
  '/users': typeof AppUsersRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/health': typeof ApiHealthRoute
  '/advance-payments/$id': typeof AppAdvancePaymentsIdRoute
  '/advance-payments/new': typeof AppAdvancePaymentsNewRoute
  '/events/$id': typeof AppEventsIdRoute
  '/reimbursements/$id': typeof AppReimbursementsIdRoute
  '/reimbursements/new': typeof AppReimbursementsNewRoute
  '/teams/$id': typeof AppTeamsIdRoute
  '/api/attachments/download': typeof ApiAttachmentsDownloadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/log/ingest': typeof ApiLogIngestRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/advance-payments/': typeof AppAdvancePaymentsIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/reimbursements/': typeof AppReimbursementsIndexRoute
  '/teams/': typeof AppTeamsIndexRoute
  '/api/immich/thumbnail/$id': typeof ApiImmichThumbnailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/export': typeof AppExportRoute
  '/users': typeof AppUsersRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/health': typeof ApiHealthRoute
  '/advance-payments/$id': typeof AppAdvancePaymentsIdRoute
  '/advance-payments/new': typeof AppAdvancePaymentsNewRoute
  '/events/$id': typeof AppEventsIdRoute
  '/reimbursements/$id': typeof AppReimbursementsIdRoute
  '/reimbursements/new': typeof AppReimbursementsNewRoute
  '/teams/$id': typeof AppTeamsIdRoute
  '/api/attachments/download': typeof ApiAttachmentsDownloadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/log/ingest': typeof ApiLogIngestRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/advance-payments': typeof AppAdvancePaymentsIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/reimbursements': typeof AppReimbursementsIndexRoute
  '/teams': typeof AppTeamsIndexRoute
  '/api/immich/thumbnail/$id': typeof ApiImmichThumbnailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/advance-payments': typeof AppAdvancePaymentsRouteRouteWithChildren
  '/_app/events': typeof AppEventsRouteRouteWithChildren
  '/_app/reimbursements': typeof AppReimbursementsRouteRouteWithChildren
  '/_app/teams': typeof AppTeamsRouteRouteWithChildren
  '/_app/export': typeof AppExportRoute
  '/_app/users': typeof AppUsersRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/': typeof AppIndexRoute
  '/_app/advance-payments/$id': typeof AppAdvancePaymentsIdRoute
  '/_app/advance-payments/new': typeof AppAdvancePaymentsNewRoute
  '/_app/events/$id': typeof AppEventsIdRoute
  '/_app/reimbursements/$id': typeof AppReimbursementsIdRoute
  '/_app/reimbursements/new': typeof AppReimbursementsNewRoute
  '/_app/teams/$id': typeof AppTeamsIdRoute
  '/api/attachments/download': typeof ApiAttachmentsDownloadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/log/ingest': typeof ApiLogIngestRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/_app/advance-payments/': typeof AppAdvancePaymentsIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/reimbursements/': typeof AppReimbursementsIndexRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
  '/api/immich/thumbnail/$id': typeof ApiImmichThumbnailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advance-payments'
    | '/events'
    | '/reimbursements'
    | '/teams'
    | '/export'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/api/avatar'
    | '/api/health'
    | '/advance-payments/$id'
    | '/advance-payments/new'
    | '/events/$id'
    | '/reimbursements/$id'
    | '/reimbursements/new'
    | '/teams/$id'
    | '/api/attachments/download'
    | '/api/auth/$'
    | '/api/log/ingest'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/advance-payments/'
    | '/events/'
    | '/reimbursements/'
    | '/teams/'
    | '/api/immich/thumbnail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/export'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/api/avatar'
    | '/api/health'
    | '/advance-payments/$id'
    | '/advance-payments/new'
    | '/events/$id'
    | '/reimbursements/$id'
    | '/reimbursements/new'
    | '/teams/$id'
    | '/api/attachments/download'
    | '/api/auth/$'
    | '/api/log/ingest'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/advance-payments'
    | '/events'
    | '/reimbursements'
    | '/teams'
    | '/api/immich/thumbnail/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/advance-payments'
    | '/_app/events'
    | '/_app/reimbursements'
    | '/_app/teams'
    | '/_app/export'
    | '/_app/users'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/api/avatar'
    | '/api/health'
    | '/_app/'
    | '/_app/advance-payments/$id'
    | '/_app/advance-payments/new'
    | '/_app/events/$id'
    | '/_app/reimbursements/$id'
    | '/_app/reimbursements/new'
    | '/_app/teams/$id'
    | '/api/attachments/download'
    | '/api/auth/$'
    | '/api/log/ingest'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/_app/advance-payments/'
    | '/_app/events/'
    | '/_app/reimbursements/'
    | '/_app/teams/'
    | '/api/immich/thumbnail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAttachmentsDownloadRoute: typeof ApiAttachmentsDownloadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLogIngestRoute: typeof ApiLogIngestRoute
  ApiZeroMutateRoute: typeof ApiZeroMutateRoute
  ApiZeroQueryRoute: typeof ApiZeroQueryRoute
  ApiImmichThumbnailIdRoute: typeof ApiImmichThumbnailIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reimbursements': {
      id: '/_app/reimbursements'
      path: '/reimbursements'
      fullPath: '/reimbursements'
      preLoaderRoute: typeof AppReimbursementsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advance-payments': {
      id: '/_app/advance-payments'
      path: '/advance-payments'
      fullPath: '/advance-payments'
      preLoaderRoute: typeof AppAdvancePaymentsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppTeamsRouteRoute
    }
    '/_app/reimbursements/': {
      id: '/_app/reimbursements/'
      path: '/'
      fullPath: '/reimbursements/'
      preLoaderRoute: typeof AppReimbursementsIndexRouteImport
      parentRoute: typeof AppReimbursementsRouteRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppEventsRouteRoute
    }
    '/_app/advance-payments/': {
      id: '/_app/advance-payments/'
      path: '/'
      fullPath: '/advance-payments/'
      preLoaderRoute: typeof AppAdvancePaymentsIndexRouteImport
      parentRoute: typeof AppAdvancePaymentsRouteRoute
    }
    '/api/zero/query': {
      id: '/api/zero/query'
      path: '/api/zero/query'
      fullPath: '/api/zero/query'
      preLoaderRoute: typeof ApiZeroQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zero/mutate': {
      id: '/api/zero/mutate'
      path: '/api/zero/mutate'
      fullPath: '/api/zero/mutate'
      preLoaderRoute: typeof ApiZeroMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/log/ingest': {
      id: '/api/log/ingest'
      path: '/api/log/ingest'
      fullPath: '/api/log/ingest'
      preLoaderRoute: typeof ApiLogIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/download': {
      id: '/api/attachments/download'
      path: '/api/attachments/download'
      fullPath: '/api/attachments/download'
      preLoaderRoute: typeof ApiAttachmentsDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/teams/$id': {
      id: '/_app/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof AppTeamsIdRouteImport
      parentRoute: typeof AppTeamsRouteRoute
    }
    '/_app/reimbursements/new': {
      id: '/_app/reimbursements/new'
      path: '/new'
      fullPath: '/reimbursements/new'
      preLoaderRoute: typeof AppReimbursementsNewRouteImport
      parentRoute: typeof AppReimbursementsRouteRoute
    }
    '/_app/reimbursements/$id': {
      id: '/_app/reimbursements/$id'
      path: '/$id'
      fullPath: '/reimbursements/$id'
      preLoaderRoute: typeof AppReimbursementsIdRouteImport
      parentRoute: typeof AppReimbursementsRouteRoute
    }
    '/_app/events/$id': {
      id: '/_app/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AppEventsIdRouteImport
      parentRoute: typeof AppEventsRouteRoute
    }
    '/_app/advance-payments/new': {
      id: '/_app/advance-payments/new'
      path: '/new'
      fullPath: '/advance-payments/new'
      preLoaderRoute: typeof AppAdvancePaymentsNewRouteImport
      parentRoute: typeof AppAdvancePaymentsRouteRoute
    }
    '/_app/advance-payments/$id': {
      id: '/_app/advance-payments/$id'
      path: '/$id'
      fullPath: '/advance-payments/$id'
      preLoaderRoute: typeof AppAdvancePaymentsIdRouteImport
      parentRoute: typeof AppAdvancePaymentsRouteRoute
    }
    '/api/immich/thumbnail/$id': {
      id: '/api/immich/thumbnail/$id'
      path: '/api/immich/thumbnail/$id'
      fullPath: '/api/immich/thumbnail/$id'
      preLoaderRoute: typeof ApiImmichThumbnailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdvancePaymentsRouteRouteChildren {
  AppAdvancePaymentsIdRoute: typeof AppAdvancePaymentsIdRoute
  AppAdvancePaymentsNewRoute: typeof AppAdvancePaymentsNewRoute
  AppAdvancePaymentsIndexRoute: typeof AppAdvancePaymentsIndexRoute
}

const AppAdvancePaymentsRouteRouteChildren: AppAdvancePaymentsRouteRouteChildren =
  {
    AppAdvancePaymentsIdRoute: AppAdvancePaymentsIdRoute,
    AppAdvancePaymentsNewRoute: AppAdvancePaymentsNewRoute,
    AppAdvancePaymentsIndexRoute: AppAdvancePaymentsIndexRoute,
  }

const AppAdvancePaymentsRouteRouteWithChildren =
  AppAdvancePaymentsRouteRoute._addFileChildren(
    AppAdvancePaymentsRouteRouteChildren,
  )

interface AppEventsRouteRouteChildren {
  AppEventsIdRoute: typeof AppEventsIdRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppEventsRouteRouteChildren: AppEventsRouteRouteChildren = {
  AppEventsIdRoute: AppEventsIdRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppEventsRouteRouteWithChildren = AppEventsRouteRoute._addFileChildren(
  AppEventsRouteRouteChildren,
)

interface AppReimbursementsRouteRouteChildren {
  AppReimbursementsIdRoute: typeof AppReimbursementsIdRoute
  AppReimbursementsNewRoute: typeof AppReimbursementsNewRoute
  AppReimbursementsIndexRoute: typeof AppReimbursementsIndexRoute
}

const AppReimbursementsRouteRouteChildren: AppReimbursementsRouteRouteChildren =
  {
    AppReimbursementsIdRoute: AppReimbursementsIdRoute,
    AppReimbursementsNewRoute: AppReimbursementsNewRoute,
    AppReimbursementsIndexRoute: AppReimbursementsIndexRoute,
  }

const AppReimbursementsRouteRouteWithChildren =
  AppReimbursementsRouteRoute._addFileChildren(
    AppReimbursementsRouteRouteChildren,
  )

interface AppTeamsRouteRouteChildren {
  AppTeamsIdRoute: typeof AppTeamsIdRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
}

const AppTeamsRouteRouteChildren: AppTeamsRouteRouteChildren = {
  AppTeamsIdRoute: AppTeamsIdRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
}

const AppTeamsRouteRouteWithChildren = AppTeamsRouteRoute._addFileChildren(
  AppTeamsRouteRouteChildren,
)

interface AppRouteChildren {
  AppAdvancePaymentsRouteRoute: typeof AppAdvancePaymentsRouteRouteWithChildren
  AppEventsRouteRoute: typeof AppEventsRouteRouteWithChildren
  AppReimbursementsRouteRoute: typeof AppReimbursementsRouteRouteWithChildren
  AppTeamsRouteRoute: typeof AppTeamsRouteRouteWithChildren
  AppExportRoute: typeof AppExportRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvancePaymentsRouteRoute: AppAdvancePaymentsRouteRouteWithChildren,
  AppEventsRouteRoute: AppEventsRouteRouteWithChildren,
  AppReimbursementsRouteRoute: AppReimbursementsRouteRouteWithChildren,
  AppTeamsRouteRoute: AppTeamsRouteRouteWithChildren,
  AppExportRoute: AppExportRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAttachmentsDownloadRoute: ApiAttachmentsDownloadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLogIngestRoute: ApiLogIngestRoute,
  ApiZeroMutateRoute: ApiZeroMutateRoute,
  ApiZeroQueryRoute: ApiZeroQueryRoute,
  ApiImmichThumbnailIdRoute: ApiImmichThumbnailIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
