/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppScheduledMessagesRouteImport } from './routes/_app/scheduled-messages'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppExportRouteImport } from './routes/_app/export'
import { Route as AppVendorsRouteRouteImport } from './routes/_app/vendors/route'
import { Route as AppVendorPaymentsRouteRouteImport } from './routes/_app/vendor-payments/route'
import { Route as AppTeamsRouteRouteImport } from './routes/_app/teams/route'
import { Route as AppReimbursementsRouteRouteImport } from './routes/_app/reimbursements/route'
import { Route as AppEventsRouteRouteImport } from './routes/_app/events/route'
import { Route as ApiJobsIndexRouteImport } from './routes/api/jobs/index'
import { Route as AppVendorsIndexRouteImport } from './routes/_app/vendors/index'
import { Route as AppVendorPaymentsIndexRouteImport } from './routes/_app/vendor-payments/index'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AppReimbursementsIndexRouteImport } from './routes/_app/reimbursements/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as ApiZeroQueryRouteImport } from './routes/api/zero/query'
import { Route as ApiZeroMutateRouteImport } from './routes/api/zero/mutate'
import { Route as ApiLogIngestRouteImport } from './routes/api/log/ingest'
import { Route as ApiJobsStatsRouteImport } from './routes/api/jobs/stats'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAttachmentsDownloadRouteImport } from './routes/api/attachments/download'
import { Route as AppVendorPaymentsNewRouteImport } from './routes/_app/vendor-payments/new'
import { Route as AppVendorPaymentsIdRouteImport } from './routes/_app/vendor-payments/$id'
import { Route as AppTeamsIdRouteImport } from './routes/_app/teams/$id'
import { Route as AppReimbursementsNewRouteImport } from './routes/_app/reimbursements/new'
import { Route as AppReimbursementsIdRouteImport } from './routes/_app/reimbursements/$id'
import { Route as AppEventsIdRouteImport } from './routes/_app/events/$id'
import { Route as AppSettingsRolesRouteRouteImport } from './routes/_app/settings/roles/route'
import { Route as AppSettingsRolesIndexRouteImport } from './routes/_app/settings/roles/index'
import { Route as ApiJobsIdRetryRouteImport } from './routes/api/jobs/$id/retry'
import { Route as ApiJobsIdCancelRouteImport } from './routes/api/jobs/$id/cancel'
import { Route as ApiImmichThumbnailIdRouteImport } from './routes/api/immich/thumbnail.$id'
import { Route as ApiImmichOriginalIdRouteImport } from './routes/api/immich/original.$id'
import { Route as AppSettingsRolesRoleIdRouteImport } from './routes/_app/settings/roles/$roleId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduledMessagesRoute = AppScheduledMessagesRouteImport.update({
  id: '/scheduled-messages',
  path: '/scheduled-messages',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRouteRoute = AppVendorsRouteRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorPaymentsRouteRoute = AppVendorPaymentsRouteRouteImport.update({
  id: '/vendor-payments',
  path: '/vendor-payments',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRouteRoute = AppTeamsRouteRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppReimbursementsRouteRoute = AppReimbursementsRouteRouteImport.update({
  id: '/reimbursements',
  path: '/reimbursements',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRouteRoute = AppEventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorsIndexRoute = AppVendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVendorsRouteRoute,
} as any)
const AppVendorPaymentsIndexRoute = AppVendorPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVendorPaymentsRouteRoute,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeamsRouteRoute,
} as any)
const AppReimbursementsIndexRoute = AppReimbursementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReimbursementsRouteRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventsRouteRoute,
} as any)
const ApiZeroQueryRoute = ApiZeroQueryRouteImport.update({
  id: '/api/zero/query',
  path: '/api/zero/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeroMutateRoute = ApiZeroMutateRouteImport.update({
  id: '/api/zero/mutate',
  path: '/api/zero/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogIngestRoute = ApiLogIngestRouteImport.update({
  id: '/api/log/ingest',
  path: '/api/log/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsStatsRoute = ApiJobsStatsRouteImport.update({
  id: '/api/jobs/stats',
  path: '/api/jobs/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/api/jobs/$id',
  path: '/api/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsDownloadRoute = ApiAttachmentsDownloadRouteImport.update({
  id: '/api/attachments/download',
  path: '/api/attachments/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorPaymentsNewRoute = AppVendorPaymentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppVendorPaymentsRouteRoute,
} as any)
const AppVendorPaymentsIdRoute = AppVendorPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVendorPaymentsRouteRoute,
} as any)
const AppTeamsIdRoute = AppTeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTeamsRouteRoute,
} as any)
const AppReimbursementsNewRoute = AppReimbursementsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppReimbursementsRouteRoute,
} as any)
const AppReimbursementsIdRoute = AppReimbursementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReimbursementsRouteRoute,
} as any)
const AppEventsIdRoute = AppEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEventsRouteRoute,
} as any)
const AppSettingsRolesRouteRoute = AppSettingsRolesRouteRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesIndexRoute = AppSettingsRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRolesRouteRoute,
} as any)
const ApiJobsIdRetryRoute = ApiJobsIdRetryRouteImport.update({
  id: '/retry',
  path: '/retry',
  getParentRoute: () => ApiJobsIdRoute,
} as any)
const ApiJobsIdCancelRoute = ApiJobsIdCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => ApiJobsIdRoute,
} as any)
const ApiImmichThumbnailIdRoute = ApiImmichThumbnailIdRouteImport.update({
  id: '/api/immich/thumbnail/$id',
  path: '/api/immich/thumbnail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImmichOriginalIdRoute = ApiImmichOriginalIdRouteImport.update({
  id: '/api/immich/original/$id',
  path: '/api/immich/original/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRolesRoleIdRoute = AppSettingsRolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => AppSettingsRolesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/events': typeof AppEventsRouteRouteWithChildren
  '/reimbursements': typeof AppReimbursementsRouteRouteWithChildren
  '/teams': typeof AppTeamsRouteRouteWithChildren
  '/vendor-payments': typeof AppVendorPaymentsRouteRouteWithChildren
  '/vendors': typeof AppVendorsRouteRouteWithChildren
  '/export': typeof AppExportRoute
  '/jobs': typeof AppJobsRoute
  '/scheduled-messages': typeof AppScheduledMessagesRoute
  '/users': typeof AppUsersRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/health': typeof ApiHealthRoute
  '/settings/roles': typeof AppSettingsRolesRouteRouteWithChildren
  '/events/$id': typeof AppEventsIdRoute
  '/reimbursements/$id': typeof AppReimbursementsIdRoute
  '/reimbursements/new': typeof AppReimbursementsNewRoute
  '/teams/$id': typeof AppTeamsIdRoute
  '/vendor-payments/$id': typeof AppVendorPaymentsIdRoute
  '/vendor-payments/new': typeof AppVendorPaymentsNewRoute
  '/api/attachments/download': typeof ApiAttachmentsDownloadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/stats': typeof ApiJobsStatsRoute
  '/api/log/ingest': typeof ApiLogIngestRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/events/': typeof AppEventsIndexRoute
  '/reimbursements/': typeof AppReimbursementsIndexRoute
  '/teams/': typeof AppTeamsIndexRoute
  '/vendor-payments/': typeof AppVendorPaymentsIndexRoute
  '/vendors/': typeof AppVendorsIndexRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/settings/roles/$roleId': typeof AppSettingsRolesRoleIdRoute
  '/api/immich/original/$id': typeof ApiImmichOriginalIdRoute
  '/api/immich/thumbnail/$id': typeof ApiImmichThumbnailIdRoute
  '/api/jobs/$id/cancel': typeof ApiJobsIdCancelRoute
  '/api/jobs/$id/retry': typeof ApiJobsIdRetryRoute
  '/settings/roles/': typeof AppSettingsRolesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/export': typeof AppExportRoute
  '/jobs': typeof AppJobsRoute
  '/scheduled-messages': typeof AppScheduledMessagesRoute
  '/users': typeof AppUsersRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/health': typeof ApiHealthRoute
  '/events/$id': typeof AppEventsIdRoute
  '/reimbursements/$id': typeof AppReimbursementsIdRoute
  '/reimbursements/new': typeof AppReimbursementsNewRoute
  '/teams/$id': typeof AppTeamsIdRoute
  '/vendor-payments/$id': typeof AppVendorPaymentsIdRoute
  '/vendor-payments/new': typeof AppVendorPaymentsNewRoute
  '/api/attachments/download': typeof ApiAttachmentsDownloadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/stats': typeof ApiJobsStatsRoute
  '/api/log/ingest': typeof ApiLogIngestRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/events': typeof AppEventsIndexRoute
  '/reimbursements': typeof AppReimbursementsIndexRoute
  '/teams': typeof AppTeamsIndexRoute
  '/vendor-payments': typeof AppVendorPaymentsIndexRoute
  '/vendors': typeof AppVendorsIndexRoute
  '/api/jobs': typeof ApiJobsIndexRoute
  '/settings/roles/$roleId': typeof AppSettingsRolesRoleIdRoute
  '/api/immich/original/$id': typeof ApiImmichOriginalIdRoute
  '/api/immich/thumbnail/$id': typeof ApiImmichThumbnailIdRoute
  '/api/jobs/$id/cancel': typeof ApiJobsIdCancelRoute
  '/api/jobs/$id/retry': typeof ApiJobsIdRetryRoute
  '/settings/roles': typeof AppSettingsRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/events': typeof AppEventsRouteRouteWithChildren
  '/_app/reimbursements': typeof AppReimbursementsRouteRouteWithChildren
  '/_app/teams': typeof AppTeamsRouteRouteWithChildren
  '/_app/vendor-payments': typeof AppVendorPaymentsRouteRouteWithChildren
  '/_app/vendors': typeof AppVendorsRouteRouteWithChildren
  '/_app/export': typeof AppExportRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/scheduled-messages': typeof AppScheduledMessagesRoute
  '/_app/users': typeof AppUsersRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/roles': typeof AppSettingsRolesRouteRouteWithChildren
  '/_app/events/$id': typeof AppEventsIdRoute
  '/_app/reimbursements/$id': typeof AppReimbursementsIdRoute
  '/_app/reimbursements/new': typeof AppReimbursementsNewRoute
  '/_app/teams/$id': typeof AppTeamsIdRoute
  '/_app/vendor-payments/$id': typeof AppVendorPaymentsIdRoute
  '/_app/vendor-payments/new': typeof AppVendorPaymentsNewRoute
  '/api/attachments/download': typeof ApiAttachmentsDownloadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/stats': typeof ApiJobsStatsRoute
  '/api/log/ingest': typeof ApiLogIngestRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/reimbursements/': typeof AppReimbursementsIndexRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
  '/_app/vendor-payments/': typeof AppVendorPaymentsIndexRoute
  '/_app/vendors/': typeof AppVendorsIndexRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/_app/settings/roles/$roleId': typeof AppSettingsRolesRoleIdRoute
  '/api/immich/original/$id': typeof ApiImmichOriginalIdRoute
  '/api/immich/thumbnail/$id': typeof ApiImmichThumbnailIdRoute
  '/api/jobs/$id/cancel': typeof ApiJobsIdCancelRoute
  '/api/jobs/$id/retry': typeof ApiJobsIdRetryRoute
  '/_app/settings/roles/': typeof AppSettingsRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/reimbursements'
    | '/teams'
    | '/vendor-payments'
    | '/vendors'
    | '/export'
    | '/jobs'
    | '/scheduled-messages'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/api/avatar'
    | '/api/health'
    | '/settings/roles'
    | '/events/$id'
    | '/reimbursements/$id'
    | '/reimbursements/new'
    | '/teams/$id'
    | '/vendor-payments/$id'
    | '/vendor-payments/new'
    | '/api/attachments/download'
    | '/api/auth/$'
    | '/api/jobs/$id'
    | '/api/jobs/stats'
    | '/api/log/ingest'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/events/'
    | '/reimbursements/'
    | '/teams/'
    | '/vendor-payments/'
    | '/vendors/'
    | '/api/jobs/'
    | '/settings/roles/$roleId'
    | '/api/immich/original/$id'
    | '/api/immich/thumbnail/$id'
    | '/api/jobs/$id/cancel'
    | '/api/jobs/$id/retry'
    | '/settings/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/export'
    | '/jobs'
    | '/scheduled-messages'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/api/avatar'
    | '/api/health'
    | '/events/$id'
    | '/reimbursements/$id'
    | '/reimbursements/new'
    | '/teams/$id'
    | '/vendor-payments/$id'
    | '/vendor-payments/new'
    | '/api/attachments/download'
    | '/api/auth/$'
    | '/api/jobs/$id'
    | '/api/jobs/stats'
    | '/api/log/ingest'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/events'
    | '/reimbursements'
    | '/teams'
    | '/vendor-payments'
    | '/vendors'
    | '/api/jobs'
    | '/settings/roles/$roleId'
    | '/api/immich/original/$id'
    | '/api/immich/thumbnail/$id'
    | '/api/jobs/$id/cancel'
    | '/api/jobs/$id/retry'
    | '/settings/roles'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/events'
    | '/_app/reimbursements'
    | '/_app/teams'
    | '/_app/vendor-payments'
    | '/_app/vendors'
    | '/_app/export'
    | '/_app/jobs'
    | '/_app/scheduled-messages'
    | '/_app/users'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/api/avatar'
    | '/api/health'
    | '/_app/'
    | '/_app/settings/roles'
    | '/_app/events/$id'
    | '/_app/reimbursements/$id'
    | '/_app/reimbursements/new'
    | '/_app/teams/$id'
    | '/_app/vendor-payments/$id'
    | '/_app/vendor-payments/new'
    | '/api/attachments/download'
    | '/api/auth/$'
    | '/api/jobs/$id'
    | '/api/jobs/stats'
    | '/api/log/ingest'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/_app/events/'
    | '/_app/reimbursements/'
    | '/_app/teams/'
    | '/_app/vendor-payments/'
    | '/_app/vendors/'
    | '/api/jobs/'
    | '/_app/settings/roles/$roleId'
    | '/api/immich/original/$id'
    | '/api/immich/thumbnail/$id'
    | '/api/jobs/$id/cancel'
    | '/api/jobs/$id/retry'
    | '/_app/settings/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAttachmentsDownloadRoute: typeof ApiAttachmentsDownloadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiJobsIdRoute: typeof ApiJobsIdRouteWithChildren
  ApiJobsStatsRoute: typeof ApiJobsStatsRoute
  ApiLogIngestRoute: typeof ApiLogIngestRoute
  ApiZeroMutateRoute: typeof ApiZeroMutateRoute
  ApiZeroQueryRoute: typeof ApiZeroQueryRoute
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
  ApiImmichOriginalIdRoute: typeof ApiImmichOriginalIdRoute
  ApiImmichThumbnailIdRoute: typeof ApiImmichThumbnailIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scheduled-messages': {
      id: '/_app/scheduled-messages'
      path: '/scheduled-messages'
      fullPath: '/scheduled-messages'
      preLoaderRoute: typeof AppScheduledMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor-payments': {
      id: '/_app/vendor-payments'
      path: '/vendor-payments'
      fullPath: '/vendor-payments'
      preLoaderRoute: typeof AppVendorPaymentsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reimbursements': {
      id: '/_app/reimbursements'
      path: '/reimbursements'
      fullPath: '/reimbursements'
      preLoaderRoute: typeof AppReimbursementsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendors/': {
      id: '/_app/vendors/'
      path: '/'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AppVendorsIndexRouteImport
      parentRoute: typeof AppVendorsRouteRoute
    }
    '/_app/vendor-payments/': {
      id: '/_app/vendor-payments/'
      path: '/'
      fullPath: '/vendor-payments/'
      preLoaderRoute: typeof AppVendorPaymentsIndexRouteImport
      parentRoute: typeof AppVendorPaymentsRouteRoute
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppTeamsRouteRoute
    }
    '/_app/reimbursements/': {
      id: '/_app/reimbursements/'
      path: '/'
      fullPath: '/reimbursements/'
      preLoaderRoute: typeof AppReimbursementsIndexRouteImport
      parentRoute: typeof AppReimbursementsRouteRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppEventsRouteRoute
    }
    '/api/zero/query': {
      id: '/api/zero/query'
      path: '/api/zero/query'
      fullPath: '/api/zero/query'
      preLoaderRoute: typeof ApiZeroQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zero/mutate': {
      id: '/api/zero/mutate'
      path: '/api/zero/mutate'
      fullPath: '/api/zero/mutate'
      preLoaderRoute: typeof ApiZeroMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/log/ingest': {
      id: '/api/log/ingest'
      path: '/api/log/ingest'
      fullPath: '/api/log/ingest'
      preLoaderRoute: typeof ApiLogIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/stats': {
      id: '/api/jobs/stats'
      path: '/api/jobs/stats'
      fullPath: '/api/jobs/stats'
      preLoaderRoute: typeof ApiJobsStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/api/jobs/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/download': {
      id: '/api/attachments/download'
      path: '/api/attachments/download'
      fullPath: '/api/attachments/download'
      preLoaderRoute: typeof ApiAttachmentsDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendor-payments/new': {
      id: '/_app/vendor-payments/new'
      path: '/new'
      fullPath: '/vendor-payments/new'
      preLoaderRoute: typeof AppVendorPaymentsNewRouteImport
      parentRoute: typeof AppVendorPaymentsRouteRoute
    }
    '/_app/vendor-payments/$id': {
      id: '/_app/vendor-payments/$id'
      path: '/$id'
      fullPath: '/vendor-payments/$id'
      preLoaderRoute: typeof AppVendorPaymentsIdRouteImport
      parentRoute: typeof AppVendorPaymentsRouteRoute
    }
    '/_app/teams/$id': {
      id: '/_app/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof AppTeamsIdRouteImport
      parentRoute: typeof AppTeamsRouteRoute
    }
    '/_app/reimbursements/new': {
      id: '/_app/reimbursements/new'
      path: '/new'
      fullPath: '/reimbursements/new'
      preLoaderRoute: typeof AppReimbursementsNewRouteImport
      parentRoute: typeof AppReimbursementsRouteRoute
    }
    '/_app/reimbursements/$id': {
      id: '/_app/reimbursements/$id'
      path: '/$id'
      fullPath: '/reimbursements/$id'
      preLoaderRoute: typeof AppReimbursementsIdRouteImport
      parentRoute: typeof AppReimbursementsRouteRoute
    }
    '/_app/events/$id': {
      id: '/_app/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AppEventsIdRouteImport
      parentRoute: typeof AppEventsRouteRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/roles/': {
      id: '/_app/settings/roles/'
      path: '/'
      fullPath: '/settings/roles/'
      preLoaderRoute: typeof AppSettingsRolesIndexRouteImport
      parentRoute: typeof AppSettingsRolesRouteRoute
    }
    '/api/jobs/$id/retry': {
      id: '/api/jobs/$id/retry'
      path: '/retry'
      fullPath: '/api/jobs/$id/retry'
      preLoaderRoute: typeof ApiJobsIdRetryRouteImport
      parentRoute: typeof ApiJobsIdRoute
    }
    '/api/jobs/$id/cancel': {
      id: '/api/jobs/$id/cancel'
      path: '/cancel'
      fullPath: '/api/jobs/$id/cancel'
      preLoaderRoute: typeof ApiJobsIdCancelRouteImport
      parentRoute: typeof ApiJobsIdRoute
    }
    '/api/immich/thumbnail/$id': {
      id: '/api/immich/thumbnail/$id'
      path: '/api/immich/thumbnail/$id'
      fullPath: '/api/immich/thumbnail/$id'
      preLoaderRoute: typeof ApiImmichThumbnailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/immich/original/$id': {
      id: '/api/immich/original/$id'
      path: '/api/immich/original/$id'
      fullPath: '/api/immich/original/$id'
      preLoaderRoute: typeof ApiImmichOriginalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/roles/$roleId': {
      id: '/_app/settings/roles/$roleId'
      path: '/$roleId'
      fullPath: '/settings/roles/$roleId'
      preLoaderRoute: typeof AppSettingsRolesRoleIdRouteImport
      parentRoute: typeof AppSettingsRolesRouteRoute
    }
  }
}

interface AppEventsRouteRouteChildren {
  AppEventsIdRoute: typeof AppEventsIdRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppEventsRouteRouteChildren: AppEventsRouteRouteChildren = {
  AppEventsIdRoute: AppEventsIdRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppEventsRouteRouteWithChildren = AppEventsRouteRoute._addFileChildren(
  AppEventsRouteRouteChildren,
)

interface AppReimbursementsRouteRouteChildren {
  AppReimbursementsIdRoute: typeof AppReimbursementsIdRoute
  AppReimbursementsNewRoute: typeof AppReimbursementsNewRoute
  AppReimbursementsIndexRoute: typeof AppReimbursementsIndexRoute
}

const AppReimbursementsRouteRouteChildren: AppReimbursementsRouteRouteChildren =
  {
    AppReimbursementsIdRoute: AppReimbursementsIdRoute,
    AppReimbursementsNewRoute: AppReimbursementsNewRoute,
    AppReimbursementsIndexRoute: AppReimbursementsIndexRoute,
  }

const AppReimbursementsRouteRouteWithChildren =
  AppReimbursementsRouteRoute._addFileChildren(
    AppReimbursementsRouteRouteChildren,
  )

interface AppTeamsRouteRouteChildren {
  AppTeamsIdRoute: typeof AppTeamsIdRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
}

const AppTeamsRouteRouteChildren: AppTeamsRouteRouteChildren = {
  AppTeamsIdRoute: AppTeamsIdRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
}

const AppTeamsRouteRouteWithChildren = AppTeamsRouteRoute._addFileChildren(
  AppTeamsRouteRouteChildren,
)

interface AppVendorPaymentsRouteRouteChildren {
  AppVendorPaymentsIdRoute: typeof AppVendorPaymentsIdRoute
  AppVendorPaymentsNewRoute: typeof AppVendorPaymentsNewRoute
  AppVendorPaymentsIndexRoute: typeof AppVendorPaymentsIndexRoute
}

const AppVendorPaymentsRouteRouteChildren: AppVendorPaymentsRouteRouteChildren =
  {
    AppVendorPaymentsIdRoute: AppVendorPaymentsIdRoute,
    AppVendorPaymentsNewRoute: AppVendorPaymentsNewRoute,
    AppVendorPaymentsIndexRoute: AppVendorPaymentsIndexRoute,
  }

const AppVendorPaymentsRouteRouteWithChildren =
  AppVendorPaymentsRouteRoute._addFileChildren(
    AppVendorPaymentsRouteRouteChildren,
  )

interface AppVendorsRouteRouteChildren {
  AppVendorsIndexRoute: typeof AppVendorsIndexRoute
}

const AppVendorsRouteRouteChildren: AppVendorsRouteRouteChildren = {
  AppVendorsIndexRoute: AppVendorsIndexRoute,
}

const AppVendorsRouteRouteWithChildren = AppVendorsRouteRoute._addFileChildren(
  AppVendorsRouteRouteChildren,
)

interface AppSettingsRolesRouteRouteChildren {
  AppSettingsRolesRoleIdRoute: typeof AppSettingsRolesRoleIdRoute
  AppSettingsRolesIndexRoute: typeof AppSettingsRolesIndexRoute
}

const AppSettingsRolesRouteRouteChildren: AppSettingsRolesRouteRouteChildren = {
  AppSettingsRolesRoleIdRoute: AppSettingsRolesRoleIdRoute,
  AppSettingsRolesIndexRoute: AppSettingsRolesIndexRoute,
}

const AppSettingsRolesRouteRouteWithChildren =
  AppSettingsRolesRouteRoute._addFileChildren(
    AppSettingsRolesRouteRouteChildren,
  )

interface AppRouteChildren {
  AppEventsRouteRoute: typeof AppEventsRouteRouteWithChildren
  AppReimbursementsRouteRoute: typeof AppReimbursementsRouteRouteWithChildren
  AppTeamsRouteRoute: typeof AppTeamsRouteRouteWithChildren
  AppVendorPaymentsRouteRoute: typeof AppVendorPaymentsRouteRouteWithChildren
  AppVendorsRouteRoute: typeof AppVendorsRouteRouteWithChildren
  AppExportRoute: typeof AppExportRoute
  AppJobsRoute: typeof AppJobsRoute
  AppScheduledMessagesRoute: typeof AppScheduledMessagesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsRolesRouteRoute: typeof AppSettingsRolesRouteRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppEventsRouteRoute: AppEventsRouteRouteWithChildren,
  AppReimbursementsRouteRoute: AppReimbursementsRouteRouteWithChildren,
  AppTeamsRouteRoute: AppTeamsRouteRouteWithChildren,
  AppVendorPaymentsRouteRoute: AppVendorPaymentsRouteRouteWithChildren,
  AppVendorsRouteRoute: AppVendorsRouteRouteWithChildren,
  AppExportRoute: AppExportRoute,
  AppJobsRoute: AppJobsRoute,
  AppScheduledMessagesRoute: AppScheduledMessagesRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsRolesRouteRoute: AppSettingsRolesRouteRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiJobsIdRouteChildren {
  ApiJobsIdCancelRoute: typeof ApiJobsIdCancelRoute
  ApiJobsIdRetryRoute: typeof ApiJobsIdRetryRoute
}

const ApiJobsIdRouteChildren: ApiJobsIdRouteChildren = {
  ApiJobsIdCancelRoute: ApiJobsIdCancelRoute,
  ApiJobsIdRetryRoute: ApiJobsIdRetryRoute,
}

const ApiJobsIdRouteWithChildren = ApiJobsIdRoute._addFileChildren(
  ApiJobsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAttachmentsDownloadRoute: ApiAttachmentsDownloadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiJobsIdRoute: ApiJobsIdRouteWithChildren,
  ApiJobsStatsRoute: ApiJobsStatsRoute,
  ApiLogIngestRoute: ApiLogIngestRoute,
  ApiZeroMutateRoute: ApiZeroMutateRoute,
  ApiZeroQueryRoute: ApiZeroQueryRoute,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
  ApiImmichOriginalIdRoute: ApiImmichOriginalIdRoute,
  ApiImmichThumbnailIdRoute: ApiImmichThumbnailIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
