#!/bin/bash
# Sets up a git worktree for parallel development.
#
# Usage:
#   bun run worktree:setup <ID>              # ID 1-9, computes ports
#   bun run worktree:setup <ID> --isolated-db  # Also creates an isolated Postgres
#
# What it does:
#   1. Copies .env from main worktree if missing
#   2. Computes ports from ID (base + ID x 10)
#   3. Writes .env.worktree with port overrides + .worktree-id
#   4. Optionally starts an isolated Postgres container
#   5. Runs bun install
#   6. Runs bun run ruler:apply
#   7. If --isolated-db: pushes schema and seeds dev data

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=./worktree-ports.sh
source "$REPO_ROOT/scripts/worktree-ports.sh"

# Parse arguments
WORKTREE_ID=""
ISOLATED_DB=false

for arg in "$@"; do
  case "$arg" in
    --isolated-db) ISOLATED_DB=true ;;
    [0-9]*) WORKTREE_ID="$arg" ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done

if [ -z "$WORKTREE_ID" ]; then
  echo "Usage: bun run worktree:setup <ID> [--isolated-db]"
  echo "  ID: 1-9 (0 is reserved for main checkout)"
  exit 1
fi

if [ "$WORKTREE_ID" -eq 0 ]; then
  echo "ID 0 is the main checkout. No setup needed."
  exit 0
fi

if [ "$WORKTREE_ID" -lt 1 ] || [ "$WORKTREE_ID" -gt 9 ]; then
  echo "Error: ID must be 1-9"
  exit 1
fi

echo "Setting up worktree with ID=$WORKTREE_ID..."

# ── Step 1: Copy .env ────────────────────────────────────────────────────────
MAIN_DIR=$(git worktree list --porcelain 2>/dev/null | head -1 | sed 's/worktree //')
if [ ! -f "$REPO_ROOT/.env" ] && [ -n "$MAIN_DIR" ] && [ -f "$MAIN_DIR/.env" ]; then
  cp "$MAIN_DIR/.env" "$REPO_ROOT/.env"
  echo "✓ Copied .env from main worktree"
elif [ -f "$REPO_ROOT/.env" ]; then
  echo "✓ .env already exists"
else
  echo "⚠ Warning: No .env found in main worktree at $MAIN_DIR"
fi

# Load .env for DEV_DB_PASSWORD (needed for isolated DB compose file)
if [ -f "$REPO_ROOT/.env" ]; then
  set -a
  # shellcheck source=/dev/null
  . "$REPO_ROOT/.env"
  set +a
fi

# ── Step 2: Compute ports ────────────────────────────────────────────────────
compute_ports "$WORKTREE_ID"

# ── Step 3: Write .worktree-id + .env.worktree ──────────────────────────────
echo "$WORKTREE_ID" > "$REPO_ROOT/.worktree-id"
echo "✓ Wrote .worktree-id ($WORKTREE_ID)"

ENV_WORKTREE="$REPO_ROOT/.env.worktree"
cat > "$ENV_WORKTREE" <<EOF
# Auto-generated by scripts/worktree-setup.sh — do not edit
WORKTREE_ID=$WORKTREE_ID
DEV_WEB_PORT=$DEV_WEB_PORT
ZERO_PORT=$ZERO_PORT
BETTER_AUTH_URL=$WT_BETTER_AUTH_URL
CORS_ORIGIN=$WT_CORS_ORIGIN
ZERO_MUTATE_URL=$WT_ZERO_MUTATE_URL
ZERO_QUERY_URL=$WT_ZERO_QUERY_URL
VITE_ZERO_URL=$WT_VITE_ZERO_URL
ZERO_REPLICA_FILE=$WT_ZERO_REPLICA_FILE
ZERO_APP_ID=zero_wt${WORKTREE_ID}
EOF

# ── Step 4: Start isolated DB container (before bun install, so it's ready) ──
DB_PORT=""
DB_CONTAINER=""
DB_COMPOSE=""
ISOLATED_DB_URL=""

if [ "$ISOLATED_DB" = true ]; then
  DB_PORT=$ISOLATED_DB_PORT
  DB_CONTAINER="pi-dash-postgres-wt${WORKTREE_ID}"
  DB_VOLUME="pi-dash_postgres_wt${WORKTREE_ID}_data"
  DB_COMPOSE="$REPO_ROOT/packages/db/docker-compose.wt${WORKTREE_ID}.yml"
  ISOLATED_DB_URL="postgres://postgres:${DEV_DB_PASSWORD}@localhost:${DB_PORT}/pi-dash"

  # Append DB overrides to .env.worktree
  cat >> "$ENV_WORKTREE" <<EOF

# Isolated database (--isolated-db)
DEV_DB_HOST=localhost:$DB_PORT
DATABASE_URL=postgres://postgres:\${DEV_DB_PASSWORD}@localhost:$DB_PORT/pi-dash
ZERO_UPSTREAM_DB=postgres://postgres:\${DEV_DB_PASSWORD}@localhost:$DB_PORT/pi-dash
ZERO_CVR_DB=postgres://postgres:\${DEV_DB_PASSWORD}@localhost:$DB_PORT/pi-dash
ZERO_CHANGE_DB=postgres://postgres:\${DEV_DB_PASSWORD}@localhost:$DB_PORT/pi-dash
EOF

  # Generate docker-compose file
  cat > "$DB_COMPOSE" <<YAML
name: pi-dash-wt${WORKTREE_ID}
services:
  postgres:
    image: postgres:17
    container_name: ${DB_CONTAINER}
    environment:
      POSTGRES_DB: pi-dash
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${DEV_DB_PASSWORD}"
    command: postgres -c wal_level=logical -c max_connections=300
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  ${DB_VOLUME}:
YAML

  echo "✓ Generated docker-compose at $DB_COMPOSE"

  # Start container (runs while bun install happens)
  echo "Starting isolated Postgres on port $DB_PORT..."
  docker compose -f "$DB_COMPOSE" up -d postgres
fi

echo "✓ Wrote .env.worktree"

# ── Step 5: Install dependencies ─────────────────────────────────────────────
echo "Installing dependencies..."
(cd "$REPO_ROOT" && bun install)
echo "✓ Dependencies installed"

# ── Step 6: Regenerate Ruler files ───────────────────────────────────────────
echo "Regenerating Ruler files (CLAUDE.md, AGENTS.md, etc.)..."
(cd "$REPO_ROOT" && bun run ruler:apply 2>/dev/null) || echo "⚠ ruler:apply failed (non-critical)"
echo "✓ Ruler files regenerated"

# ── Step 7: Migrations + seed (after deps installed, DB should be ready) ─────
if [ "$ISOLATED_DB" = true ]; then
  # Wait for DB to be ready
  echo "Waiting for isolated DB..."
  WAIT=0
  until docker exec "$DB_CONTAINER" pg_isready -U postgres 2>/dev/null; do
    sleep 1
    WAIT=$((WAIT + 1))
    if [ "$WAIT" -ge 30 ]; then
      echo "Error: Isolated DB failed to become ready within 30s"
      exit 1
    fi
  done
  echo "✓ Isolated Postgres ready on port $DB_PORT"

  # Push schema
  echo "Pushing schema to isolated DB..."
  (cd "$REPO_ROOT/packages/db" && DATABASE_URL="$ISOLATED_DB_URL" SKIP_VALIDATION=true bunx drizzle-kit push)
  echo "✓ Schema pushed"

  # Seed dev data
  echo "Seeding dev data..."
  (cd "$REPO_ROOT/packages/e2e" && DATABASE_URL="$ISOLATED_DB_URL" SKIP_VALIDATION=true bun run helpers/seed-dev-data.ts)
  echo "✓ Dev data seeded"
fi

# ── Summary ──────────────────────────────────────────────────────────────────
print_port_summary "$WORKTREE_ID"

echo ""
echo "Worktree ready! Start developing with:"
echo "  bun run dev        # Starts web on :$DEV_WEB_PORT + zero on :$ZERO_PORT"
echo "  bun run dev:web    # Just the web server on :$DEV_WEB_PORT"
